### PR TITLE
agent-ui: reference other process in segment

### PR DESCRIPTION
**Pull request by bejito**
This change is [Reviewable](https://reviewable.io/reviews/stratumn/indigo-js/158)

### CODE REVIEW

**Comment by bejito** [comment]
*[a discussion](https://reviewable.io:443/reviews/stratumn/indigo-js/158#-L-Wj3s0hIcAxpWRdLiB:-L-Wj3s0hIcAxpWRdLiC:bvlopiy) (no related file):*
The user will have to first select a process in order to be able to choose between its segments:




---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/158)*

**Comment by conord33** [comment]
Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[packages/agent-ui/src/components/segmentsFilter.js, line 38 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/158#-L-X3Au8_lVBzMjQ-5FS:-L-X3Au8_lVBzMjQ-5FT:b-7apdv4) ([raw file](https://github.com/stratumn/indigo-js/blob/e60434f08a9e135822643eac70c128dc83ca64d4/packages/agent-ui/src/components/segmentsFilter.js#L38)):*
> ```JavaScript
>       prevLinkHash,
>       valid: validatePrevLinkHash(prevLinkHash),
>       process: props.currentProcess
> ```

you can pull off currentProcess  from props above with filters.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/158)*

**Comment by bejito** [comment]
*[packages/agent-ui/src/components/segmentsFilter.js, line 38 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/158#-L-X3Au8_lVBzMjQ-5FS:-L-X7q8pZIdyU_2bJtoF:b-atadnx) ([raw file](https://github.com/stratumn/indigo-js/blob/e60434f08a9e135822643eac70c128dc83ca64d4/packages/agent-ui/src/components/segmentsFilter.js#L38)):*
<details><summary><i>Previously, conord33 (Conor Dawson) wrote…</i></summary><blockquote>

you can pull off currentProcess  from props above with filters.
</blockquote></details>

yeah right, I can pass it in my case as a default filter value

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/158)*

**Comment by bejito** [comment]
*[packages/agent-ui/src/components/segmentsFilter.js, line 38 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/158#-L-X3Au8_lVBzMjQ-5FS:-L-X9og1QbbZkYw3duuE:bid4tr1) ([raw file](https://github.com/stratumn/indigo-js/blob/e60434f08a9e135822643eac70c128dc83ca64d4/packages/agent-ui/src/components/segmentsFilter.js#L38)):*
<details><summary><i>Previously, bejito (Mourad BEJI) wrote…</i></summary><blockquote>

yeah right, I can pass it in my case as a default filter value
</blockquote></details>

Well, that's actually not very convenient. Since the component is not entirely controlled, passing filters by props will overwrite the internal state. So the easiest option would be to store the filters in the parent component, and thus to make it stateful. Not sure we want to have so many stateful components there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/158)*

**Comment by conord33** [comment]
Review status: 0 of 12 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[packages/agent-ui/src/components/segmentsFilter.js, line 31 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/158#-L-XAUcuXtF6adEYpZDX:-L-XAUcuXtF6adEYpZDY:bwu0mjt) ([raw file](https://github.com/stratumn/indigo-js/blob/e60434f08a9e135822643eac70c128dc83ca64d4/packages/agent-ui/src/components/segmentsFilter.js#L31)):*
> ```JavaScript
>   constructor(props) {
>     super(props);
>     const { filters } = props;
> ```

and this one to `const { filters, currentProcess } = props;`

---

*[packages/agent-ui/src/components/segmentsFilter.js, line 38 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/158#-L-X3Au8_lVBzMjQ-5FS:-L-XAKt7nTkA5DYkgnGp:b-3aqas0) ([raw file](https://github.com/stratumn/indigo-js/blob/e60434f08a9e135822643eac70c128dc83ca64d4/packages/agent-ui/src/components/segmentsFilter.js#L38)):*
<details><summary><i>Previously, bejito (Mourad BEJI) wrote…</i></summary><blockquote>

Well, that's actually not very convenient. Since the component is not entirely controlled, passing filters by props will overwrite the internal state. So the easiest option would be to store the filters in the parent component, and thus to make it stateful. Not sure we want to have so many stateful components there.
</blockquote></details>

sorry i was unclear, i meant you could just change this line to `process: currentProcess`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/158)*

**Comment by bejito** [comment]
*[packages/agent-ui/src/components/segmentsFilter.js, line 38 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/158#-L-X3Au8_lVBzMjQ-5FS:-L-XB4lrFCj3dCyMUplA:b-bcy46x) ([raw file](https://github.com/stratumn/indigo-js/blob/e60434f08a9e135822643eac70c128dc83ca64d4/packages/agent-ui/src/components/segmentsFilter.js#L38)):*
<details><summary><i>Previously, conord33 (Conor Dawson) wrote…</i></summary><blockquote>

sorry i was unclear, i meant you could just change this line to `process: currentProcess`
</blockquote></details>

oh yes, sorry didn't understand that :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/158)*

**Comment by conord33** [comment]
Review status: 0 of 12 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[packages/agent-ui/src/components/segmentsFilter.js, line 38 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/158#-L-X3Au8_lVBzMjQ-5FS:-L-XBg2Hws-Iw_VDytNb:bn21ian) ([raw file](https://github.com/stratumn/indigo-js/blob/e60434f08a9e135822643eac70c128dc83ca64d4/packages/agent-ui/src/components/segmentsFilter.js#L38)):*
<details><summary><i>Previously, bejito (Mourad BEJI) wrote…</i></summary><blockquote>

oh yes, sorry didn't understand that :+1: 
</blockquote></details>

no worries, that was a shitty sentence, i guess i need to work on my english too :wink: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/158)*

**Comment by t-bast** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[packages/agent-ui/src/components/segmentsFilter.js, line 62 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/158#-L-XDHy_pYpmYPuk1rrB:-L-XDHy_pYpmYPuk1rrC:b-c04btg) ([raw file](https://github.com/stratumn/indigo-js/blob/e60434f08a9e135822643eac70c128dc83ca64d4/packages/agent-ui/src/components/segmentsFilter.js#L62)):*
> ```JavaScript
>   }
> 
>   selectProcess(e) {
> ```

Why don't you use the handleChange method?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/158)*

**Comment by bejito** [comment]
*[packages/agent-ui/src/components/segmentsFilter.js, line 62 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/158#-L-XDHy_pYpmYPuk1rrB:-L-XGA1mm-EqsbH_s7j3:b-shqp0t) ([raw file](https://github.com/stratumn/indigo-js/blob/e60434f08a9e135822643eac70c128dc83ca64d4/packages/agent-ui/src/components/segmentsFilter.js#L62)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Why don't you use the handleChange method?
</blockquote></details>

Hmm, the callback was different at first, but I guess now handleChange will do exactly what I want

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/158)*

**Comment by bejito** [comment]
*[packages/agent-ui/src/components/segmentsFilter.js, line 62 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/158#-L-XDHy_pYpmYPuk1rrB:-L-XGkCe5HWI2auo1exw:bq2m18u) ([raw file](https://github.com/stratumn/indigo-js/blob/e60434f08a9e135822643eac70c128dc83ca64d4/packages/agent-ui/src/components/segmentsFilter.js#L62)):*
<details><summary><i>Previously, bejito (Mourad BEJI) wrote…</i></summary><blockquote>

Hmm, the callback was different at first, but I guess now handleChange will do exactly what I want
</blockquote></details>

actually the callback is a prop in the child component. Creating the onClick on the fly will make the child component rerender each time this one is rerendered

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/158)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/158#-:-L-XIiplLE5WsSZdj45s:bnfp4nl)*

**Comment by such** [comment]
:lgtm:

---

Reviewed 11 of 12 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/158#-:-L-XPlDukRHOOXfZZAH-:bnfp4nl)*

**Pull request merged**
