### PR TITLE
agent-ui: segments filter

### PR DESCRIPTION
**Pull request by jeremie-stratumn**
This change is [Reviewable](https://reviewable.io/reviews/stratumn/indigo-js/119)

### CODE REVIEW

**Comment by t-bast** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[packages/agent-ui/src/containers/contentPage.js, line 31 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/119#-Kyp_3b8ite_aAiPEaNx:-Kyp_3b8ite_aAiPEaNy:b-iihwv) ([raw file](https://github.com/stratumn/indigo-js/blob/4662880132f570e99b6755e145a7f113289905db/packages/agent-ui/src/containers/contentPage.js#L31)):*
> ```JavaScript
>     <Route exact path="/:agent/:process" component={ProcessInfoPage} />
>     <Route exact path="/:agent/:process/maps" component={ProcessMapsPage} />
>     <Route exact path="/:agent/:process/segments" component={SegmentsFilter} />
> ```

It's a bit weird that we have two components for the exact same route (the SegmentsFilter and the ProcessSegmentsPage).
I think it would make more sense to integrate the segments filter component inside the ProcessSegmentsPage don't you think?

---

*[packages/agent-ui/src/containers/processSegmentsPage.js, line 28 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/119#-Kyp_mkrr6mvY2PG_tsf:-Kyp_mkrr6mvY2PG_tsg:b-gmdkn4) ([raw file](https://github.com/stratumn/indigo-js/blob/4662880132f570e99b6755e145a7f113289905db/packages/agent-ui/src/containers/processSegmentsPage.js#L28)):*
> ```JavaScript
>       thisFilters !== filters
>     ) {
>       fetchSegments(agent, process, parse(filters));
> ```

nit: maybe it should be fetchSegments' responsibility to call 'parse' on the filters - this way we're sure it's done in only one place but done for every call

---

*[packages/agent-ui/src/containers/segmentsFilter.js, line 10 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/119#-KypbBngWtQg4gbHzjrg:-KypbBnh3vibONmhM7Vv:b4rc8j9) ([raw file](https://github.com/stratumn/indigo-js/blob/4662880132f570e99b6755e145a7f113289905db/packages/agent-ui/src/containers/segmentsFilter.js#L10)):*
> ```JavaScript
> export const SegmentsFilter = ({ pathname, search }) => {
>   let { mapIds, tags, prevLinkHash } = parse(search);
>   if (typeof mapIds !== 'object') {
> ```

nit: why is that needed?

---

*[packages/agent-ui/src/containers/segmentsFilter.test.js, line 13 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/119#-Kypbc944bJby6LKDjrM:-Kypbc944bJby6LKDjrN:b-y9kp0b) ([raw file](https://github.com/stratumn/indigo-js/blob/4662880132f570e99b6755e145a7f113289905db/packages/agent-ui/src/containers/segmentsFilter.test.js#L13)):*
> ```JavaScript
> chai.use(sinonChai);
> 
> describe('<SegmentFilter />', () => {
> ```

nit: missing 's': SegmentsFilter

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/119)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[packages/agent-ui/src/containers/segmentsFilter.js, line 8 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/119#-KypeamB55YXgJeEnvn9:-KypeamC2AMp27uCyK1l:b-wnczkc) ([raw file](https://github.com/stratumn/indigo-js/blob/4662880132f570e99b6755e145a7f113289905db/packages/agent-ui/src/containers/segmentsFilter.js#L8)):*
> ```JavaScript
> import history from '../store/history';
> 
> export const SegmentsFilter = ({ pathname, search }) => {
> ```

I'd like to start separating components and containers. It looks like this is really a component, not a container (it doesn't need to inspect the redux state and will receive the route params as props directly). Can you try moving this to the components folder, remove the "connect" and the "withRouter" ? It will also make testing more isolated

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/119)*

**Comment by jeremie-stratumn** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[packages/agent-ui/src/containers/contentPage.js, line 31 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/119#-Kyp_3b8ite_aAiPEaNx:-Kypo8LPORvRKVcTn_R2:blse3nz) ([raw file](https://github.com/stratumn/indigo-js/blob/4662880132f570e99b6755e145a7f113289905db/packages/agent-ui/src/containers/contentPage.js#L31)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

It's a bit weird that we have two components for the exact same route (the SegmentsFilter and the ProcessSegmentsPage).
I think it would make more sense to integrate the segments filter component inside the ProcessSegmentsPage don't you think?
</blockquote></details>

Yes I agree, I tried that first but I had some trouble i the tests I think. Let me give it another go.

---

*[packages/agent-ui/src/containers/processSegmentsPage.js, line 28 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/119#-Kyp_mkrr6mvY2PG_tsf:-KypoJ5l9BU-ZNWx5ETx:bd6cvqk) ([raw file](https://github.com/stratumn/indigo-js/blob/4662880132f570e99b6755e145a7f113289905db/packages/agent-ui/src/containers/processSegmentsPage.js#L28)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit: maybe it should be fetchSegments' responsibility to call 'parse' on the filters - this way we're sure it's done in only one place but done for every call
</blockquote></details>

good idea!

---

*[packages/agent-ui/src/containers/segmentsFilter.js, line 8 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/119#-KypeamB55YXgJeEnvn9:-Kypo_e60vdjE26UXdwn:b-tforbd) ([raw file](https://github.com/stratumn/indigo-js/blob/4662880132f570e99b6755e145a7f113289905db/packages/agent-ui/src/containers/segmentsFilter.js#L8)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

I'd like to start separating components and containers. It looks like this is really a component, not a container (it doesn't need to inspect the redux state and will receive the route params as props directly). Can you try moving this to the components folder, remove the "connect" and the "withRouter" ? It will also make testing more isolated
</blockquote></details>

I agree I should be able to get rid of `connect` and `withRouter`. But do you think that components should be able to mess up with `history`? which is the case for this guy..

---

*[packages/agent-ui/src/containers/segmentsFilter.js, line 10 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/119#-KypbBngWtQg4gbHzjrg:-Kypoq6cd-UC39uIE7qy:bqb96pl) ([raw file](https://github.com/stratumn/indigo-js/blob/4662880132f570e99b6755e145a7f113289905db/packages/agent-ui/src/containers/segmentsFilter.js#L10)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit: why is that needed?
</blockquote></details>

I should replace this with `Array.isArray(mapIds)`. Basically, `mapIds` should be an array, but if the user writes the querystring himself, it is possible that the `qs` library decode it not as an array. For example, this is a valid querystring for a `mapIds` array of 1 element: `?mapIds[]=foo`. Now this will lead to `mapIds=['foo']`, all good. But if someone inputs the following querystring in the url: `?mapIds=foo`, this leads to `mapIds='foo'` which is not an array and the line below fails later on:
```
defaultValue={mapIds && mapIds.join(' ')}
```
because `join` is not a string function..

So I make sure that that `tags` and `mapIds` are arrays (will change for `Array.isArray`).

---

*[packages/agent-ui/src/containers/segmentsFilter.test.js, line 13 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/119#-Kypbc944bJby6LKDjrM:-KypqFJhWR04TL-K6sZs:b-pb9bue) ([raw file](https://github.com/stratumn/indigo-js/blob/4662880132f570e99b6755e145a7f113289905db/packages/agent-ui/src/containers/segmentsFilter.test.js#L13)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit: missing 's': SegmentsFilter
</blockquote></details>

indeed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/119)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[packages/agent-ui/src/containers/segmentsFilter.js, line 8 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/119#-KypeamB55YXgJeEnvn9:-Kypu9D1mL5qGBioEaKt:brbou8r) ([raw file](https://github.com/stratumn/indigo-js/blob/4662880132f570e99b6755e145a7f113289905db/packages/agent-ui/src/containers/segmentsFilter.js#L8)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

I agree I should be able to get rid of `connect` and `withRouter`. But do you think that components should be able to mess up with `history`? which is the case for this guy..
</blockquote></details>

I think it should be ok since it doesn't have to know about redux or router to use history.

---

*[packages/agent-ui/src/containers/segmentsFilter.js, line 10 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/119#-KypbBngWtQg4gbHzjrg:-KypuUf-88T6zbXRLEE7:b948p4i) ([raw file](https://github.com/stratumn/indigo-js/blob/4662880132f570e99b6755e145a7f113289905db/packages/agent-ui/src/containers/segmentsFilter.js#L10)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

I should replace this with `Array.isArray(mapIds)`. Basically, `mapIds` should be an array, but if the user writes the querystring himself, it is possible that the `qs` library decode it not as an array. For example, this is a valid querystring for a `mapIds` array of 1 element: `?mapIds[]=foo`. Now this will lead to `mapIds=['foo']`, all good. But if someone inputs the following querystring in the url: `?mapIds=foo`, this leads to `mapIds='foo'` which is not an array and the line below fails later on:
```
defaultValue={mapIds && mapIds.join(' ')}
```
because `join` is not a string function..

So I make sure that that `tags` and `mapIds` are arrays (will change for `Array.isArray`).
</blockquote></details>

Ok makes sense, thanks !

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/119)*

**Comment by jeremie-stratumn** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[packages/agent-ui/src/containers/processSegmentsPage.js, line 28 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/119#-Kyp_mkrr6mvY2PG_tsf:-KypttCof7OsIEo-4H0J:bwq2jl8) ([raw file](https://github.com/stratumn/indigo-js/blob/4662880132f570e99b6755e145a7f113289905db/packages/agent-ui/src/containers/processSegmentsPage.js#L28)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

good idea!
</blockquote></details>

Looking at this a bit more, I dont think `fetchSegments` should do the `parse` because the querystring encoding is an implementation detail between the browser and the container (`ProcessSegmentsPage`). I think this `parse` is the responsability of the `mapStateToProps` function of this class. Once I move the `SegmentsFilter` to be a pure component, this component won't have to call `parse`, only `ProcessSegmentsPage` will.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/119)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[packages/agent-ui/src/containers/processSegmentsPage.js, line 28 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/119#-Kyp_mkrr6mvY2PG_tsf:-Kyq6A4USGNvq1atxxl2:bdnerpx) ([raw file](https://github.com/stratumn/indigo-js/blob/4662880132f570e99b6755e145a7f113289905db/packages/agent-ui/src/containers/processSegmentsPage.js#L28)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

Looking at this a bit more, I dont think `fetchSegments` should do the `parse` because the querystring encoding is an implementation detail between the browser and the container (`ProcessSegmentsPage`). I think this `parse` is the responsability of the `mapStateToProps` function of this class. Once I move the `SegmentsFilter` to be a pure component, this component won't have to call `parse`, only `ProcessSegmentsPage` will.
</blockquote></details>

Sounds good !

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/119)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 1 of 9 files at r1, 4 of 4 files at r2, 19 of 20 files at r3, 5 of 9 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[packages/agent-ui/src/components/segmentsFilter.js, line 19 at r5](https://reviewable.io:443/reviews/stratumn/indigo-js/119#-Kyu2UxIEFLS47KQTYr9:-Kyu2UxIEFLS47KQTYrA:b-hbm1gx) ([raw file](https://github.com/stratumn/indigo-js/blob/5672a7b1fe1e7880e0a62a657111c92bc965a1a3/packages/agent-ui/src/components/segmentsFilter.js#L19)):*
> ```JavaScript
>     super(props);
>     const { filters } = props;
>     const { mapIds, tags, prevLinkHash } = filters;
> ```

nit: you can merge these two lines in one: const { mapIds, tags, prevLinkHash } = props.filter;

---

*[packages/agent-ui/src/components/segmentsFilter.js, line 33 at r5](https://reviewable.io:443/reviews/stratumn/indigo-js/119#-Kyu2doiL9ZnIwi5eQKn:-Kyu2doiL9ZnIwi5eQKo:bxs2f0g) ([raw file](https://github.com/stratumn/indigo-js/blob/5672a7b1fe1e7880e0a62a657111c92bc965a1a3/packages/agent-ui/src/components/segmentsFilter.js#L33)):*
> ```JavaScript
>   componentWillReceiveProps(nextProps) {
>     const { filters } = nextProps;
>     const { mapIds, tags, prevLinkHash } = filters;
> ```

nit: same

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/119#-:-Kyu3vlGKpzFVw9Ra8Cj:bnfp4nl)*

**Pull request merged**
