### PR TITLE
agent-client-js: use qs for querystring encoding to handle arrays

### PR DESCRIPTION
**Pull request by jeremie-stratumn**
https://github.com/stratumn/indigo-js/issues/17

use node library qs to encode query strings which is also used by express extended query parser to decode query strings. See: http://expressjs.com/en/api.html

### CODE REVIEW

**Comment by stephan83** [comment]
So what does a serialized array look like?

**Comment by jeremie-stratumn** [comment]
qs will encode this object ` { tags: [ 'myTag', 'myTag2' ] }` like this:
`tags%5B0%5D=myTag&tags%5B1%5D=myTag2`
which is really:
`tags[0]=myTag&tags[1]=myTag2`

I believe this is compatible with https://github.com/google/go-querystring

**Comment by stephan83** [comment]
See: https://github.com/stratumn/sdk/issues/186

**Comment by stephan83** [comment]
From the go-querystring docs:

> Slice and Array values default to encoding as multiple URL values of the same name. Including the "comma" option signals that the field should be encoded as a single comma-delimited value. Including the "space" option similarly encodes the value as a single space-delimited string. Including the "semicolon" option will encode the value as a semicolon-delimited string. Including the "brackets" option signals that the multiple URL values should have "[]" appended to the value name. "numbered" will append a number to the end of each incidence of the value name, example: name0=value0&name1=value1, etc.

So I believe it can parse this format:

```
tags[]=myTag&tags[]=myTag2
```

I'm not sure it can parse the format you described (with numbers in the brackets).

**Comment by jeremie-stratumn** [comment]
qs can do that too:

```
qs.stringify({ a: ['b', 'c', 'd'] }, { indices: false });
// 'a=b&a=c&a=d'
```

see https://github.com/ljharb/qs

**Comment by stephan83** [comment]
Yes, it can also do brackets without numbers, let's  just pick one compatible with both :)

**Comment by jeremie-stratumn** [comment]
yes that one then! I'll make the change

**Comment by stephan83** [comment]
Yes I think brackets are better, hopefully that way `qs` will parse it as an array even if there is only one value.

**Comment by jeremie-stratumn** [comment]
yes that should work and this test should check that: https://github.com/stratumn/indigo-js/pull/18/files#diff-f0dcd32587ea7ba6c47eb39a7476b8cfR58

**Comment by jeremie-stratumn** [comment]
sorry this is the right example:

```
qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'brackets' })
// 'a[]=b&a[]=c'
```

you were right that the previous version was not capable to decode an array of size 1... :)

**Comment by jeremie-stratumn** [comment]
running my test I now see:
tags%5B%5D=myTag&tags%5B%5D=myTag2
tags%5B%5D=myTag

which is what we wanted

**Comment by stephan83** [comment]
I think go-querystring might expect the brackets not to be url-encoded, we'll see.

**Comment by stephan83** [comment]
Well that Go library only encodes values, it doesn't parse querystrings :(

**Comment by stephan83** [comment]
Should be good on the Go side, but we also need to rebuild all the libraries that use agent-client-js.

**Pull request merged**
