### PR TITLE
Create stratumn-cs-validator package 

### LINKED ISSUE #114: mapexplorer-core: update json library used for validations

### LINKED ISSUE #115: mapexplorer-core: extract the ChainValidator/SegmentValidator into their own package
And update them!

They could be useful on their own and they are not that useful in our usage of the Map Explorer.

### PR DESCRIPTION
**Pull request by simonvadee**
Fix #115, fix #114 

- `ChainValidator` has been renamed `MapValidator`.

- SegmentValidator has been updated to fit the new evidence format (and test fixtures were updated)

- Dependencies of mapexplorer-core and angular-mapexplorer have been updated to include the stratum-cs-validator package

- `hashJson()` now use `canonicaljson` instead of `canonical-json`

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/indigo-js/130)

### CODE REVIEW

**Comment by such** [comment]
Reviewed 70 of 70 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[packages/cs-validator/.editorconfig, line 16 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/130#-Kz-tgnOj70L7C6hoHXr:-Kz-tgnP3yL79sfAtK4K:bcck56h) ([raw file](https://github.com/stratumn/indigo-js/blob/5437f8ac0d40f1b6302ef363ccd91f19684057f4/packages/cs-validator/.editorconfig#L16)):*
> ```
> charset = utf-8
> indent_style = space
> indent_size = 2
> ```

we shouldn't need this file

---

*[packages/cs-validator/.eslintignore, line 3 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/130#-Kz-tmHPaPPmiTVr_LOQ:-Kz-tmHPaPPmiTVr_LOR:bp8v0sf) ([raw file](https://github.com/stratumn/indigo-js/blob/5437f8ac0d40f1b6302ef363ccd91f19684057f4/packages/cs-validator/.eslintignore#L3)):*
> ```
> lib
> node_modules
> dist
> ```

this file is useless as well I think (even though I guess you just copied it from mapexplorer-core)

---

*[packages/mapexplorer-core/src/ChainTree.js, line 159 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/130#-Kz-w2y100Mk_p0GeErD:-Kz-w2y100Mk_p0GeErE:bgkie5w) ([raw file](https://github.com/stratumn/indigo-js/blob/5437f8ac0d40f1b6302ef363ccd91f19684057f4/packages/mapexplorer-core/src/ChainTree.js#L159)):*
> ```JavaScript
>     const nodes = root ? root.descendants() : [];
>     const polygon = this.options.polygonSize;
>     const maxDepth = Math.max(nodes, x => x.depth) || 0;
> ```

I don't think this works: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/max

---

*[packages/mapexplorer-core/src/ChainTreeBuilder.js, line 17 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/130#-Kz-w_d9W6S6BkNXgTVZ:-Kz-w_d9W6S6BkNXgTV_:b2whqum) ([raw file](https://github.com/stratumn/indigo-js/blob/5437f8ac0d40f1b6302ef363ccd91f19684057f4/packages/mapexplorer-core/src/ChainTreeBuilder.js#L17)):*
> ```JavaScript
> */
> 
> import { resolveLinks, wrap, parseIfJson } from 'stratumn-cs-validator';
> ```

If we depend on stratumn-cs-validator only for that, I'm not sure it's worth it. `wrap` and `parseIfJson` are super small and could be duplicated. Maybe `resolveLinks` could be implemented more cleanly by `agent-client` (since we need that dependency anyway)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/130)*

**Comment by simonvadee** [comment]
Reviewed 70 of 70 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[packages/cs-validator/.editorconfig, line 16 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/130#-Kz-tgnOj70L7C6hoHXr:-Kz36BPwITbk5_T5qh21:b32w0x) ([raw file](https://github.com/stratumn/indigo-js/blob/5437f8ac0d40f1b6302ef363ccd91f19684057f4/packages/cs-validator/.editorconfig#L16)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

we shouldn't need this file
</blockquote></details>

OK

---

*[packages/cs-validator/.eslintignore, line 3 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/130#-Kz-tmHPaPPmiTVr_LOQ:-Kz36D7PcpRhmk8QQMlb:b32w0x) ([raw file](https://github.com/stratumn/indigo-js/blob/5437f8ac0d40f1b6302ef363ccd91f19684057f4/packages/cs-validator/.eslintignore#L3)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

this file is useless as well I think (even though I guess you just copied it from mapexplorer-core)
</blockquote></details>

OK

---

*[packages/mapexplorer-core/src/ChainTree.js, line 159 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/130#-Kz-w2y100Mk_p0GeErD:-Kz2ublOwKF98jWZ-gyB:bd30ifx) ([raw file](https://github.com/stratumn/indigo-js/blob/5437f8ac0d40f1b6302ef363ccd91f19684057f4/packages/mapexplorer-core/src/ChainTree.js#L159)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

I don't think this works: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/max
</blockquote></details>

good catch

---

*[packages/mapexplorer-core/src/ChainTreeBuilder.js, line 17 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/130#-Kz-w_d9W6S6BkNXgTVZ:-Kz2vEaioUStFiHfaXzP:b-15fdpu) ([raw file](https://github.com/stratumn/indigo-js/blob/5437f8ac0d40f1b6302ef363ccd91f19684057f4/packages/mapexplorer-core/src/ChainTreeBuilder.js#L17)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

If we depend on stratumn-cs-validator only for that, I'm not sure it's worth it. `wrap` and `parseIfJson` are super small and could be duplicated. Maybe `resolveLinks` could be implemented more cleanly by `agent-client` (since we need that dependency anyway)?
</blockquote></details>

You're right, it will be cleaner this way and it makes sense that `agent-client` implement `resolveLinks`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/130)*

**Comment by such** [comment]
Review status: 44 of 57 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[packages/angular-mapexplorer/rollup.browser.demo.config.js, line 18 at r2](https://reviewable.io:443/reviews/stratumn/indigo-js/130#-Kz9IGerZ167b27zbGv3:-Kz9IGerZ167b27zbGv4:bz54tni) ([raw file](https://github.com/stratumn/indigo-js/blob/fec200acc273270f103e17d0b92bf7d48ea344cb/packages/angular-mapexplorer/rollup.browser.demo.config.js#L18)):*
> ```JavaScript
>       Object.assign(
>         {
>           exclude: ['node_modules/**', '../**', 'vendor/**']
> ```

this doesn't work in the end right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/130)*

**Comment by such** [comment]
Reviewed 2 of 71 files at r1, 17 of 19 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/130)*

**Comment by simonvadee** [comment]
Reviewed 2 of 71 files at r1, 15 of 19 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[packages/angular-mapexplorer/rollup.browser.demo.config.js, line 18 at r2](https://reviewable.io:443/reviews/stratumn/indigo-js/130#-Kz9IGerZ167b27zbGv3:-Kz9mKlNHEvOJBbu4C33:b-kngltd) ([raw file](https://github.com/stratumn/indigo-js/blob/fec200acc273270f103e17d0b92bf7d48ea344cb/packages/angular-mapexplorer/rollup.browser.demo.config.js#L18)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

this doesn't work in the end right?
</blockquote></details>

It doesn't work with packages with direct dependencies to each other (mapexplorer-core, cs-validator, *-mapexplorer...) but I think that since the demo imports angular-mapexplorer directly and is built after we bootstrapped the package, the symlinks are used and everything goes fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/130)*

**Pull request merged**
