### PR TITLE
release: 0.2.0-0

### PR DESCRIPTION
**Pull request by t-bast**
Releasing 0.2.0-0 version for testing before the official 0.2.0 release

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/indigo-js/192)

### CODE REVIEW

**Comment by such** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[packages/tmpop-explorer/app/package.json, line 3 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/192#-L0p0tn7aok_D1YpjJZm:-L0p0tn7aok_D1YpjJZn:b-8r8nrm) ([raw file](https://github.com/stratumn/indigo-js/blob/914951d32667831d694f1a473faac0910fd7ca5e/packages/tmpop-explorer/app/package.json#L3)):*
> ```JSON
> {
>   "name": "tmpop-explorer-app",
>   "version": "$npm_package_version",
> ```

was it expected?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/192)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[packages/tmpop-explorer/app/package.json, line 3 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/192#-L0p0tn7aok_D1YpjJZm:-L0p16rK-P5ZXkzjCnAQ:b-k1v763) ([raw file](https://github.com/stratumn/indigo-js/blob/914951d32667831d694f1a473faac0910fd7ca5e/packages/tmpop-explorer/app/package.json#L3)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

was it expected?
</blockquote></details>

Interesting, not really :)
Looks like lerna publish can still improve a bit, I'll dig into it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/192)*

**Comment by t-bast** [comment]
Review status: 10 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[packages/tmpop-explorer/app/package.json, line 3 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/192#-L0p0tn7aok_D1YpjJZm:-L0p79Jb8iYyPF0Pqaur:bn7471a) ([raw file](https://github.com/stratumn/indigo-js/blob/914951d32667831d694f1a473faac0910fd7ca5e/packages/tmpop-explorer/app/package.json#L3)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Interesting, not really :)
Looks like lerna publish can still improve a bit, I'll dig into it
</blockquote></details>

This should work now, it needed double-quotes around the sed regex to parse variables (thank you stackoverflow)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/192)*

**Comment by such** [comment]
:lgtm:

---

Review status: 10 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/192#-:-L0p935J1sXJaIekhMD2:bnfp4nl)*

**Comment by such** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/192)*

**Pull request merged**
