### PR TITLE
Save agent version in segment

### PR DESCRIPTION
**Pull request by conord33**
This adds a plugin to save the agent version in the segments `link.meta` object. 

I also noticed when bootstrapping this project that the `yarn.lock` file of the agent-ui was updated. That is included in a separate commit. Not sure if this PR is the appropriate place for that but we should probably update the lock file.

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/indigo-js/123)

### CODE REVIEW

**Comment by t-bast** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[packages/agent-js/src/plugins/index.js, line 32 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/123#-Kyq5QgB-ZBUIYdBcy6T:-Kyq5QgB-ZBUIYdBcy6U:b-mpecjq) ([raw file](https://github.com/stratumn/indigo-js/blob/78a26ab8d57043be8023a502999a9a3b4512f55f/packages/agent-js/src/plugins/index.js#L32)):*
> ```JavaScript
>   signedState,
>   stateHash,
>   agentVersion
> ```

nit: if we could keep this list alphabetically ordered it would be nice :)

---

*[packages/agent-js/test/plugins/agentVersion.js, line 35 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/123#-Kyq5fSsZxTjEShU3Czr:-Kyq5fSsZxTjEShU3Czs:b-h68nmp) ([raw file](https://github.com/stratumn/indigo-js/blob/78a26ab8d57043be8023a502999a9a3b4512f55f/packages/agent-js/test/plugins/agentVersion.js#L35)):*
> ```JavaScript
> 
>   '#action()'(link) {
>     return (link.meta.agentVersion === null).should.be.true;
> ```

Curious: why do we want a null agent version here? Don't we want to add it in all cases?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/123)*

**Comment by conord33** [comment]
Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[packages/agent-js/test/plugins/agentVersion.js, line 35 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/123#-Kyq5fSsZxTjEShU3Czr:-KyqRH2iooqQYPWgLzkU:bx03leq) ([raw file](https://github.com/stratumn/indigo-js/blob/78a26ab8d57043be8023a502999a9a3b4512f55f/packages/agent-js/test/plugins/agentVersion.js#L35)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Curious: why do we want a null agent version here? Don't we want to add it in all cases?
</blockquote></details>

I updated this to make it set in the #action step as well. @such is there a reason to not have the agent version set in the #action step?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/123)*

**Comment by t-bast** [comment]
:lgtm: but Adrien should have a quick look at it since I don't know our plugin system yet :)

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/123#-:-Kyu0rcq1CRvxZj6Gnyz:b-dagz9y)*

**Comment by such** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[packages/agent-js/src/plugins/agentVersion.js, line 38 at r2](https://reviewable.io:443/reviews/stratumn/indigo-js/123#-Kyv25yfmKDKLp1wCNMV:-Kyv25yfmKDKLp1wCNMW:b6359vn) ([raw file](https://github.com/stratumn/indigo-js/blob/57e39f7026e4456674cdc352f853e9b96bdf7c1b/packages/agent-js/src/plugins/agentVersion.js#L38)):*
> ```JavaScript
>   willCreate(link) {
>     setAgentVersion(link);
>   }
> ```

You don't need to do it in both callbacks. Since the agent version is added in DidCreateLink, it will be saved in the store and it will be present when this callback is used (ie when a children of this segment is about to be created).

---

*[packages/agent-js/test/plugins/agentVersion.js, line 35 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/123#-Kyq5fSsZxTjEShU3Czr:-Kyv345h40q4ExlkjNgA:b-up58ix) ([raw file](https://github.com/stratumn/indigo-js/blob/78a26ab8d57043be8023a502999a9a3b4512f55f/packages/agent-js/test/plugins/agentVersion.js#L35)):*
<details><summary><i>Previously, conord33 (Conor Dawson) wrote…</i></summary><blockquote>

I updated this to make it set in the #action step as well. @such is there a reason to not have the agent version set in the #action step?
</blockquote></details>

Related to my comment before. You don't have to test this one I think. It's meant to check that your parent has been "cleaned up" when the transition function is executed. But it's useless here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/123)*

**Comment by conord33** [comment]
This should finally be ready to go! 😅

**Comment by conord33** [comment]
Will do 👍

**Pull request merged**
