### PR TITLE
mapexplorer-core: display segment references

### LINKED ISSUE #1: mapexplorer-core: display segment references
cf https://paper.dropbox.com/doc/Merge-Maps-yRLqBbu9jusqytgjvCTBD

### PR DESCRIPTION
**Pull request by simonvadee**
Fixes #1 

- ChainTree.js can display a map and its related segments.

- It is possible to switch maps directly within the map explorer by clicking on a reference segment.

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/indigo-js/104)

### CODE REVIEW

**Comment by t-bast** [comment]
Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/104)*

**Comment by such** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[packages/mapexplorer-core/package.json, line 79 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/104#-KyLb_xdlwluqIXGt5qA:-KyLb_xdlwluqIXGt5qB:ba7h59f) ([raw file](https://github.com/stratumn/indigo-js/blob/fa96d7b38b4351f45ca4be0f026d54049b784b91/packages/mapexplorer-core/package.json#L79)):*
> ```JSON
>     "js-sha256": "^0.3.0",
>     "stratumn-agent-client": "^3.0.2",
>     "stratumn-agent": "^0.18.3"
> ```

why do you need this dependency?

---

*[packages/mapexplorer-core/src/ChainTree.js, line 40 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/104#-KyLcBGZpd7R-rYqbCPX:-KyLcBGZpd7R-rYqbCPY:bgrxvxx) ([raw file](https://github.com/stratumn/indigo-js/blob/fa96d7b38b4351f45ca4be0f026d54049b784b91/packages/mapexplorer-core/src/ChainTree.js#L40)):*
> ```JavaScript
> 
>   display(chainscript, options) {
>     this.options = options;
> ```

if we want to make options an attribute of the object it would probably make more sense to pass it to the constructor. This way makes it a bit weird. We could also remove it from the `update` function signature since it is now available with `this.options`.

---

*[packages/mapexplorer-core/src/ChainTree.js, line 167 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/104#-KyLd0rKQsyifziwpyxY:-KyLd0rKQsyifziwpyxZ:bspgdmo) ([raw file](https://github.com/stratumn/indigo-js/blob/fa96d7b38b4351f45ca4be0f026d54049b784b91/packages/mapexplorer-core/src/ChainTree.js#L167)):*
> ```JavaScript
>       : 0;
>     const computedWidth = Math.max(
>       treeWidth + extraNodesWidth + options.getArrowLength() * 4,
> ```

we could be more explicit on where the magic number 4 comes from. Could it go inside a constant?

---

*[packages/mapexplorer-core/src/ChainTree.js, line 252 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/104#-KyLdKSmmimTwcm_5EoH:-KyLdKSmmimTwcm_5EoI:bnm6hnk) ([raw file](https://github.com/stratumn/indigo-js/blob/fa96d7b38b4351f45ca4be0f026d54049b784b91/packages/mapexplorer-core/src/ChainTree.js#L252)):*
>  .attr('y', refNode.x + this.options.getArrowLength() / 2 + 5)
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>
>       .attr('x', this.options.getArrowLength() / 2 - 5)
>       .attr('ry', 15)
>       .attr('rx', 15)
>       .attr('fill-opacity', 0.7)
>       .attr('width', this.options.getArrowLength() * 2 + 10)
</details>

Lots of magic numbers here!

---

*[packages/mapexplorer-core/src/ChainTree.js, line 262 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/104#-KyLdPZeEJmfPsxcthmj:-KyLdPZeEJmfPsxcthmk:b-ckh0jn) ([raw file](https://github.com/stratumn/indigo-js/blob/fa96d7b38b4351f45ca4be0f026d54049b784b91/packages/mapexplorer-core/src/ChainTree.js#L262)):*
> ```JavaScript
>       .attr('id', 'linkLabelRef')
>       .attr('dx', this.options.getArrowLength() / 2)
>       .attr('dy', refNode.x + this.options.getArrowLength() - 17)
> ```

:1234: 

---

*[packages/mapexplorer-core/src/ChainTree.js, line 297 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/104#-KyLde3CSEs2lkh0rvPg:-KyLde3CSEs2lkh0rvPh:bx5jan7) ([raw file](https://github.com/stratumn/indigo-js/blob/fa96d7b38b4351f45ca4be0f026d54049b784b91/packages/mapexplorer-core/src/ChainTree.js#L297)):*
> his.innerG
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>
>       .append('rect')
>       .attr('y', refNode.x - this.options.getBoxSize().height / 2 - 2)
>       .attr('x', refNode.y + this.options.getArrowLength() * 2 + 10)
>       .attr('ry', 15)
>       .attr('rx', 15)
>       .attr('fill-opacity', 0.7)
>       .attr('width', this.options.getArrowLength() * 2 + 10)
>       .attr('height', this.options.getBoxSize().height)
>       .attr('class', 'refLinkBox')
>       .on('click', onClick);
</details>

what prevents this code from being factorized with `drawAncestorsRef`?

---

*[packages/mapexplorer-core/src/Nodes.js, line 23 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/104#-KyLZhZH8SJbjW8dSAmr:-KyLZhZH8SJbjW8dSAms:b-26km4y) ([raw file](https://github.com/stratumn/indigo-js/blob/fa96d7b38b4351f45ca4be0f026d54049b784b91/packages/mapexplorer-core/src/Nodes.js#L23)):*
> ```JavaScript
>   let refs = [];
>   if (node && node.children) {
>     for (let i = 0; i < node.children.length; i += 1) {
> ```

is it possible to avoid the `for` loop here? with `node.children.forEach` or `node.children.map` for instance?

---

*[packages/mapexplorer-core/src/Nodes.js, line 42 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/104#-KyLZxjbpE9JdHFlCW-u:-KyLZxjbpE9JdHFlCW-v:bauiebk) ([raw file](https://github.com/stratumn/indigo-js/blob/fa96d7b38b4351f45ca4be0f026d54049b784b91/packages/mapexplorer-core/src/Nodes.js#L42)):*
> ```JavaScript
>   const nodes = root ? root.descendants() : [];
>   const refs = findNodeRefs(root);
>   for (let i = 0; i < refs.length; i += 1) {
> ```

Can we also avoid the for loop here?

---

*[packages/mapexplorer-core/src/Nodes.js, line 64 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/104#-KyL_9dg7jxEb_jh68Le:-KyL_9dg7jxEb_jh68Lf:b-uk6bno) ([raw file](https://github.com/stratumn/indigo-js/blob/fa96d7b38b4351f45ca4be0f026d54049b784b91/packages/mapexplorer-core/src/Nodes.js#L64)):*
> ```JavaScript
>           ) {
>             throw new Error(
>               `findExtraLinks: wrong reference format (should have process, mapId, linkHash)`
> ```

You are using a template here but there are no variables. It would be probably useful to add the ref.

---

*[packages/mapexplorer-core/src/Nodes.js, line 110 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/104#-KyL_nQnnd4r78AKWCz5:-KyL_nQnnd4r78AKWCz6:bekftr2) ([raw file](https://github.com/stratumn/indigo-js/blob/fa96d7b38b4351f45ca4be0f026d54049b784b91/packages/mapexplorer-core/src/Nodes.js#L110)):*
> ```JavaScript
>     return getAgent(agentUrl)
>       .then(agent => {
>         const process = agent.processes[ref.data.link.meta.process];
> ```

it would be better to use `agent.getProcess(ref.data.link.meta.process)`

---

*[packages/mapexplorer-core/src/Nodes.js, line 140 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/104#-KyLdvwCWzAx-OoidibS:-KyLdvwCWzAx-OoidibT:bga4lmg) ([raw file](https://github.com/stratumn/indigo-js/blob/fa96d7b38b4351f45ca4be0f026d54049b784b91/packages/mapexplorer-core/src/Nodes.js#L140)):*
> ```JavaScript
>             child.link.meta.prevLinkHash = ref.data.meta.linkHash;
>             child.link.meta.refs = null;
>             child.link.meta.action = 'reference';
> ```

is this useful?

---

*[packages/mapexplorer-core/src/Nodes.js, line 146 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/104#-KyLaAQqIANnPnOGmTBY:-KyLaAQqIANnPnOGmTBZ:bvh4grt) ([raw file](https://github.com/stratumn/indigo-js/blob/fa96d7b38b4351f45ca4be0f026d54049b784b91/packages/mapexplorer-core/src/Nodes.js#L146)):*
> ```JavaScript
>           });
>         const fullSegments = segments.concat(foreignChildren);
>         return fullSegments;
> ```

Do you need to declare the `fullSegments` variable here?

---

*[packages/react-mapexplorer/example/src/App.js, line 5 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/104#-KyLbE1dwYmaMMo0p0Rj:-KyLbE1dwYmaMMo0p0Rk:b-8fx2u7) ([raw file](https://github.com/stratumn/indigo-js/blob/fa96d7b38b4351f45ca4be0f026d54049b784b91/packages/react-mapexplorer/example/src/App.js#L5)):*
> ```JavaScript
> import { MapExplorer } from "react-mapexplorer";
> 
> import { chainscript } from "./chainscript";
> ```

:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/104)*

**Comment by simonvadee** [comment]
Reviewed 13 of 17 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[packages/mapexplorer-core/package.json, line 79 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/104#-KyLb_xdlwluqIXGt5qA:-KyMJABGf-jn5_E-UuIo:b-cx2y3c) ([raw file](https://github.com/stratumn/indigo-js/blob/fa96d7b38b4351f45ca4be0f026d54049b784b91/packages/mapexplorer-core/package.json#L79)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

why do you need this dependency?
</blockquote></details>

to test if the transition between maps works. I will move it to devDependencies.

---

*[packages/mapexplorer-core/src/ChainTree.js, line 252 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/104#-KyLdKSmmimTwcm_5EoH:-KyMWNOaUr5lPRDt3tpt:bj5r843) ([raw file](https://github.com/stratumn/indigo-js/blob/fa96d7b38b4351f45ca4be0f026d54049b784b91/packages/mapexplorer-core/src/ChainTree.js#L252)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

>  .attr('y', refNode.x + this.options.getArrowLength() / 2 + 5)
>       .attr('x', this.options.getArrowLength() / 2 - 5)
>       .attr('ry', 15)
>       .attr('rx', 15)
>       .attr('fill-opacity', 0.7)
>       .attr('width', this.options.getArrowLength() * 2 + 10)

Lots of magic numbers here!
</blockquote></details>

I ran into quite a lot of troubles to make the ui look "ok", and I agree it's ugly to look at. I'll add variables and factorize `drawAncestorsRef` and `drawForeignChildRef` to be DRY compliant. I'll also transform as much as possible these magic numbers into css classes.

---

*[packages/mapexplorer-core/src/Nodes.js, line 140 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/104#-KyLdvwCWzAx-OoidibS:-KyMTG0gxWmgWxr4y9Di:b-8yjx4d) ([raw file](https://github.com/stratumn/indigo-js/blob/fa96d7b38b4351f45ca4be0f026d54049b784b91/packages/mapexplorer-core/src/Nodes.js#L140)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

is this useful?
</blockquote></details>

it is: changing the action allows to change the link label to 'reference' (we also don't want to display the child references since this node is becoming a reference itself, and the prevLinkHash is used to wire the node to the map it is referenced by)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/104)*

**Comment by such** [comment]
:lgtm:

---

Reviewed 7 of 17 files at r1, 5 of 5 files at r2, 9 of 10 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[packages/mapexplorer-core/src/ChainTree.js, line 25 at r4](https://reviewable.io:443/reviews/stratumn/indigo-js/104#-KyWcW6h0ulXglM4LTUA:-KyWcW6i1fBqC4nP3aJ7:b-lqdte2) ([raw file](https://github.com/stratumn/indigo-js/blob/dee20158896b81ea0c416c9b1105ea6f1a4738e4/packages/mapexplorer-core/src/ChainTree.js#L25)):*
> ```JavaScript
> import { makeLink, finalLink, translate } from './treeUtils';
> import parseChainscript from './parseChainscript';
> import { findExtraLinks, findExtraNodes, loadRef } from './Nodes';
> ```

the file name should not start with an upper case for consistency I think

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/104#-:-KyWdLHp8U7bDD2t9-qL:bnfp4nl)*

**Pull request merged**
