### PR TITLE
agent-ui: add notifications

### PR DESCRIPTION
**Pull request by jeremie-stratumn**
ground work for https://github.com/stratumn/indigo-js/issues/27

In this PR we introduce a new part of the state, `notifications`, where all sort of notifications can be pushed. The idea is that any action should be able to add notifications to the state, and any container should be able to subscribe to notifications so that when a new notification that match specific criterias comes in, that container can update (or do something else) and eventually send another action to remove that notification since it has been "seen".

The first example of that pattern is the `MapPage` component. After appending a new segment to the current map, on success we dispatch a new action to add a notification that a new segment for that mapId has been created. `MapPage` now implements `shouldComponentUpdate` method which returns true only if new notifications for that mapId are found. So in that case, it will return true and hence will re render (we force re rendering of mapexplorer component by setting its key to a random uuid). 

Next step is to handle websocket requests with this notification pattern.

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/indigo-js/161)

### CODE REVIEW

**Comment by t-bast** [comment]
Great work ! :lgtm_strong: 

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/161#-:-L-_nWszQ7XTZj6WEwEG:b-8bt87w)*

**Comment by conord33** [comment]
I like the pattern, I just have one small issue. Just wanted to get your guys opinion on it.

---

Review status: 13 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[packages/agent-ui/src/actions/notifications.js, line 14 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/161#-L-a2Vngaxuq__umfEw7:-L-_yJCSF7__j-FG2bMG:bvbqida) ([raw file](https://github.com/stratumn/indigo-js/blob/3898c3842f465645cb3982c4999b8289dac3a5bf/packages/agent-ui/src/actions/notifications.js#L14)):*
> ```JavaScript
> });
> 
> export const makeNotification = args => ({
> ```

do you guys think we should put these in another file since they are not really actions? I know they are closely related to the notification actions, but they dont really follow the actions pattern of returning an action or returning a thunk that will dispatch an action.  maybe we should have a helpers folder for these kind of functions?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/161#-:-L-a2yUpgEVOYsPandZC:b8b9zfs)*

**Comment by jeremie-stratumn** [comment]
Review status: 13 of 16 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[packages/agent-ui/src/actions/notifications.js, line 14 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/161#-L-a2Vngaxuq__umfEw7:-L-a4B7-jck4ZioxYYPC:byavg0c) ([raw file](https://github.com/stratumn/indigo-js/blob/3898c3842f465645cb3982c4999b8289dac3a5bf/packages/agent-ui/src/actions/notifications.js#L14)):*
<details><summary><i>Previously, conord33 (Conor Dawson) wrote…</i></summary><blockquote>

do you guys think we should put these in another file since they are not really actions? I know they are closely related to the notification actions, but they dont really follow the actions pattern of returning an action or returning a thunk that will dispatch an action.  maybe we should have a helpers folder for these kind of functions?
</blockquote></details>

I agree, I hesitated in putting it here and I was lazy. We could have it under the `utils` folder? Or create a `helpers` folder for that purpose..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/161)*

**Comment by conord33** [comment]
Review status: 13 of 16 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[packages/agent-ui/src/actions/notifications.js, line 14 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/161#-L-a2Vngaxuq__umfEw7:-L-a59m5pFmhSs5tBWh2:b-7r4fud) ([raw file](https://github.com/stratumn/indigo-js/blob/3898c3842f465645cb3982c4999b8289dac3a5bf/packages/agent-ui/src/actions/notifications.js#L14)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

I agree, I hesitated in putting it here and I was lazy. We could have it under the `utils` folder? Or create a `helpers` folder for that purpose..
</blockquote></details>

i think utils is a good spot. those are basically our helper functions right now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/161)*

**Comment by bejito** [comment]
*[packages/agent-ui/src/containers/mapPage.js, line 18 at r2](https://reviewable.io:443/reviews/stratumn/indigo-js/161#-L-aCO53Wf47GdE1Q2ne:-L-aCO53Wf47GdE1Q2nf:b-wun291) ([raw file](https://github.com/stratumn/indigo-js/blob/4a70889c6c6ed49dd458daacea4e1b4b1dbced0b/packages/agent-ui/src/containers/mapPage.js#L18)):*
> ```JavaScript
>   componentDidUpdate() {
>     const { notifications, removeSegmentNotifications } = this.props;
>     if (notifications.length > 0) {
> ```

If you are here, it should mean that we already passed shouldComponentUpdate right ? notifications length should always be >0 at this point.
Btw, you can always map on an empty list

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/161)*

**Comment by jeremie-stratumn** [comment]
Review status: 9 of 18 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[packages/agent-ui/src/containers/mapPage.js, line 18 at r2](https://reviewable.io:443/reviews/stratumn/indigo-js/161#-L-aCO53Wf47GdE1Q2ne:-L-aRYwZG4OjF5AmF6xk:b-ii5pkz) ([raw file](https://github.com/stratumn/indigo-js/blob/4a70889c6c6ed49dd458daacea4e1b4b1dbced0b/packages/agent-ui/src/containers/mapPage.js#L18)):*
<details><summary><i>Previously, bejito (Mourad BEJI) wrote…</i></summary><blockquote>

If you are here, it should mean that we already passed shouldComponentUpdate right ? notifications length should always be >0 at this point.
Btw, you can always map on an empty list
</blockquote></details>

you are right! let me change that

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/161)*

**Comment by bejito** [comment]
:lgtm: :+1:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/161#-:-L-ahhw4cmZ8c8HOYIKV:bbf4361)*

**Pull request merged**
