### PR TITLE
react-mapexplorer: update to new Tendermint Proof format

### PR DESCRIPTION
**Pull request by such**
This change is [Reviewable](https://reviewable.io/reviews/stratumn/indigo-js/175)

### CODE REVIEW

**Comment by t-bast** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[packages/react-mapexplorer/src/TMPopEvidence.js, line 49 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/175#-L0KrNLaJczEku7Vg-vI:-L0KrNLaJczEku7Vg-vJ:bnde7w7) ([raw file](https://github.com/stratumn/indigo-js/blob/7c3b7f32986b2a3afa80dd8382f9767dd9450485/packages/react-mapexplorer/src/TMPopEvidence.js#L49)):*
> ```JavaScript
> 
>           <h4>App Hash</h4>
>           <p>{evidence.proof.header.app_hash}</p>
> ```

I think the appHash that reflects the changes is in nextHeader right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/175)*

**Comment by such** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[packages/react-mapexplorer/src/TMPopEvidence.js, line 49 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/175#-L0KrNLaJczEku7Vg-vI:-L0KwhHY7R4m-_BALprh:b7dnpb3) ([raw file](https://github.com/stratumn/indigo-js/blob/7c3b7f32986b2a3afa80dd8382f9767dd9450485/packages/react-mapexplorer/src/TMPopEvidence.js#L49)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

I think the appHash that reflects the changes is in nextHeader right?
</blockquote></details>

right! thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/175)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/175#-:-L0KxMlUGDzw5yNFlSI0:bnfp4nl)*

**Comment by t-bast** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/175)*

**Pull request merged**
