### PR TITLE
agent-ui: start adding material UI

### PR DESCRIPTION
**Pull request by t-bast**
Start styling our app with Material UI components.
There are a few gotchas to learn, but overall I think that once ramped-up Material UI is a good choice.
In this PR I style:
  * the global layout (left drawer, top bar and app frame)
  * the dialogs
Since those went well, I'm pretty confident we won't have anything blocking when styling our other components.
This PR is unfortunately a bit big, but I needed to make sure the global layout of the app and the active components (dialogs) would work well with Material UI.

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/indigo-js/132)

### CODE REVIEW

**Comment by such** [comment]
:lgtm:

---

Reviewed 27 of 27 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/132#-:-Kz4I6vIbTGhvXAEJE28:bnfp4nl)*

**Comment by jeremie-stratumn** [comment]
Do you know if there is a way to define style (theme?) at top level app and have it pass through to all our components so that we don't have to manually import the style from styles folder in each component?

---

Reviewed 27 of 27 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[packages/agent-ui/src/components/actionArgumentFields.js, line 7 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/132#-Kz7sNgfN9UuNSUlDr_s:-Kz7sNgfN9UuNSUlDr_t:b-ngu0dg) ([raw file](https://github.com/stratumn/indigo-js/blob/2a2455975159a82d667afcbd1d99d884deb69025/packages/agent-ui/src/components/actionArgumentFields.js#L7)):*
> ```JavaScript
> 
> export const ActionArgumentFields = ({ args, valueChanged }) => {
>   const valueFields = [...Array(args.length)];
> ```

Just one quick comment here on the JS choices. You could have used the more compact:
```
args.map(argName => <TextField ... />)
```
And no need to init `valueFields` with this syntax. I find it nicer than the old school `for (let i=0...)`

---

*[packages/agent-ui/src/components/topBarButton.js, line 10 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/132#-Kz7tw4QMn4h1RHmFRzc:-Kz7tw4QMn4h1RHmFRzd:b-vikzev) ([raw file](https://github.com/stratumn/indigo-js/blob/2a2455975159a82d667afcbd1d99d884deb69025/packages/agent-ui/src/components/topBarButton.js#L10)):*
> ```JavaScript
> import buttonStyles from '../styles/buttons';
> 
> export const TopBarButton = ({ agent, process, openDialog, text, classes }) => (
> ```

Just one thought here: you could make this even more generic, say `GenericButton`, by condensing the args `agent` `process` and `openDialog` into one `callback`. It would then be the responsability of the caller to provide the right callback. So a `TopBarButton` would be a `<GenericButton callback={() => openDialog(agent, process)} .../>`. That way, you can reuse the same Button logic throughout.. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/132#-:-Kz7v5NCHVYYUNKOvhbK:bt042js)*

**Comment by t-bast** [comment]
I don't think so, all the samples I saw require the withStyle decorator, which means we need to chose which style object we import. But I think it's better that way : each component chooses which small part of the style it needs which is more decoupled than a big style object containing all the styles.
Most of the components will not need any specific styling so they won't even need to import a style object and use the withStyles decorator.
But we will be able to customize the theme at the top-level of the app, and all the components will receive things like default text styling, colors, etc implicitly.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[packages/agent-ui/src/components/actionArgumentFields.js, line 7 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/132#-Kz7sNgfN9UuNSUlDr_s:-Kz7yf7gfR0pMRyTqKNr:b6s1l2i) ([raw file](https://github.com/stratumn/indigo-js/blob/2a2455975159a82d667afcbd1d99d884deb69025/packages/agent-ui/src/components/actionArgumentFields.js#L7)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

Just one quick comment here on the JS choices. You could have used the more compact:
```
args.map(argName => <TextField ... />)
```
And no need to init `valueFields` with this syntax. I find it nicer than the old school `for (let i=0...)`
</blockquote></details>

I'm not sure I understand your suggestion, I need the argument index to keep the ordering of the arguments correct.
So I don't think I'll be able to do that with only a map, will I?

---

*[packages/agent-ui/src/components/topBarButton.js, line 10 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/132#-Kz7tw4QMn4h1RHmFRzc:-Kz7z0RUQ-xx5UtUX-o3:b-y9oxer) ([raw file](https://github.com/stratumn/indigo-js/blob/2a2455975159a82d667afcbd1d99d884deb69025/packages/agent-ui/src/components/topBarButton.js#L10)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

Just one thought here: you could make this even more generic, say `GenericButton`, by condensing the args `agent` `process` and `openDialog` into one `callback`. It would then be the responsability of the caller to provide the right callback. So a `TopBarButton` would be a `<GenericButton callback={() => openDialog(agent, process)} .../>`. That way, you can reuse the same Button logic throughout.. 
</blockquote></details>

Good point, I like this idea. I'll do it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/132#-:-Kz7xql0WrJzYvcERRzF:b7p9nto)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[packages/agent-ui/src/components/actionArgumentFields.js, line 7 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/132#-Kz7sNgfN9UuNSUlDr_s:-Kz7zhnIMa6ml5SjzceK:b-w9lm5a) ([raw file](https://github.com/stratumn/indigo-js/blob/2a2455975159a82d667afcbd1d99d884deb69025/packages/agent-ui/src/components/actionArgumentFields.js#L7)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

I'm not sure I understand your suggestion, I need the argument index to keep the ordering of the arguments correct.
So I don't think I'll be able to do that with only a map, will I?
</blockquote></details>

It looks like map can in fact provide the index, I'll try it out

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/132)*

**Comment by jeremie-stratumn** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[packages/agent-ui/src/components/actionArgumentFields.js, line 7 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/132#-Kz7sNgfN9UuNSUlDr_s:-Kz8-8WQqEUR8Z_SKytJ:b2nign3) ([raw file](https://github.com/stratumn/indigo-js/blob/2a2455975159a82d667afcbd1d99d884deb69025/packages/agent-ui/src/components/actionArgumentFields.js#L7)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

It looks like map can in fact provide the index, I'll try it out
</blockquote></details>

yep

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/132)*

**Comment by t-bast** [comment]
Review status: 23 of 27 files reviewed at latest revision, 2 unresolved discussions.

---

*[packages/agent-ui/src/components/actionArgumentFields.js, line 7 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/132#-Kz7sNgfN9UuNSUlDr_s:-Kz81A45e36ys09P2ghT:b-896fix) ([raw file](https://github.com/stratumn/indigo-js/blob/2a2455975159a82d667afcbd1d99d884deb69025/packages/agent-ui/src/components/actionArgumentFields.js#L7)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

yep
</blockquote></details>

Done.

---

*[packages/agent-ui/src/components/topBarButton.js, line 10 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/132#-Kz7tw4QMn4h1RHmFRzc:-Kz81AkmHnQzdVwPghdd:b-896fix) ([raw file](https://github.com/stratumn/indigo-js/blob/2a2455975159a82d667afcbd1d99d884deb69025/packages/agent-ui/src/components/topBarButton.js#L10)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Good point, I like this idea. I'll do it
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/132)*

**Comment by jeremie-stratumn** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/132#-:-Kz8EkZlLXEhJ2ugfPeT:bnfp4nl)*

**Pull request merged**
