### PR TITLE
agent-ui: reference other process in segment

### PR DESCRIPTION
**Pull request by bejito**
https://github.com/stratumn/indigo-js/issues/150

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/indigo-js/153)

### CODE REVIEW

**Comment by conord33** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/153#-:-L-H1cloct9J7yP2LqGb:bnfp4nl)*

**Comment by bejito** [comment]
There is actually an issue on navigation with this:
In the map explorer, when navigating back to a ref, if that one is from another process, we still have the original segment's actions

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/153#-:-L-H4A_LFQdA-D4C-wWh:b91sdkc)*

**Comment by conord33** [comment]
do you think that is a bug with mapexplorer?

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/153#-:-L-H8qoeymlS5SI0k_j0:bpiytp3)*

**Comment by t-bast** [comment]
Reviewed 1 of 4 files at r1.
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[packages/agent-ui/src/actions/getSegments.js, line 38 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/153#-L-HEgP-H2zal0M7Igy8:-L-HEgP0486CpzmMTFH2:b-okgij6) ([raw file](https://github.com/stratumn/indigo-js/blob/74b05c16b4302efd2fc118724fe74ebdf4797a40/packages/agent-ui/src/actions/getSegments.js#L38)):*
> ```JavaScript
>           .then(segments => dispatch(getSegmentsSuccess(segments)));
>       } else {
>         // Get segments from all processes
> ```

I don't think we should do that. If you want to add a ref from another process, as a user you know which process you want to reference.
So you probably need to choose in a dropdown the process you want to pick a segment from.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/153)*

**Comment by bejito** [comment]
We allow the user to select a different process in the refs selection modal. Then, the user can select a segment in that process.




---







*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/153#-:-L-W8LUDRdG9pogkRvvk:bc4ru1s)*

**Comment by bejito** [comment]
Will actually close this PR and start a fresh one as I went back and forth on some things

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/153#-:-L-WINUU4Sm5_yLgA5jS:bkd8nvg)*

**Pull request closed without merging**
