### PR TITLE
agent-ui: append segment dialog lists actions

### PR DESCRIPTION
**Pull request by t-bast**
Create a basic append segment dialog that can be opened and closed.
List available actions in a dropdown, and populates these actions from state.

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/indigo-js/120)

### CODE REVIEW

**Comment by jeremie-stratumn** [comment]
Review status: 0 of 11 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[packages/agent-ui/src/actions/appendSegment.js, line 30 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/120#-KypjWLXcFC2UkpVMDRE:-KypjWLXcFC2UkpVMDRF:b-ttmk9z) ([raw file](https://github.com/stratumn/indigo-js/blob/fe2542b5631c4713bb97cc8469a228720bd48dc2/packages/agent-ui/src/actions/appendSegment.js#L30)):*
> ```JavaScript
>       process: processName,
>       actions: actions,
>       parent: ''
> ```

what is this for?

---

*[packages/agent-ui/src/containers/appendSegmentDialog.js, line 49 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/120#-KypkwxBCUp_tjv-L-a2:-KypkwxBCUp_tjv-L-a3:b5hb3v6) ([raw file](https://github.com/stratumn/indigo-js/blob/fe2542b5631c4713bb97cc8469a228720bd48dc2/packages/agent-ui/src/containers/appendSegmentDialog.js#L49)):*
> ```JavaScript
>         <form
>           onSubmit={e => {
>             e.preventDefault();
> ```

Shouldn't you be doing anything else on submit? Maybe for a later PR?

---

*[packages/agent-ui/src/containers/appendSegmentDialog.js, line 81 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/120#-KypkDqWwND-Nf9TgRAO:-KypkDqWwND-Nf9TgRAP:b-k960nf) ([raw file](https://github.com/stratumn/indigo-js/blob/fe2542b5631c4713bb97cc8469a228720bd48dc2/packages/agent-ui/src/containers/appendSegmentDialog.js#L81)):*
> ```JavaScript
> };
> 
> export function mapStateToProps(state) {
> ```

it seems that you only use `state.appendSegment` from state. Maybe use some ES6 destructuring from the top here? you would get rid of all the `state.*`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/120)*

**Comment by jeremie-stratumn** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/120)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[packages/agent-ui/src/actions/appendSegment.js, line 30 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/120#-KypjWLXcFC2UkpVMDRE:-KypmAWAhHwqn-Z16HS7:bqm1u5h) ([raw file](https://github.com/stratumn/indigo-js/blob/fe2542b5631c4713bb97cc8469a228720bd48dc2/packages/agent-ui/src/actions/appendSegment.js#L30)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

what is this for?
</blockquote></details>

This is the parent segment (when you append a segment, it has to be the child of an existing segment). I wanted to do everything in one PR but it turns out there are too many things to do, so currently I'm not setting this value. It will be for a next PR.

---

*[packages/agent-ui/src/containers/appendSegmentDialog.js, line 49 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/120#-KypkwxBCUp_tjv-L-a2:-KypmR0l3KJpQRbgygB5:b-s2ccxq) ([raw file](https://github.com/stratumn/indigo-js/blob/fe2542b5631c4713bb97cc8469a228720bd48dc2/packages/agent-ui/src/containers/appendSegmentDialog.js#L49)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

Shouldn't you be doing anything else on submit? Maybe for a later PR?
</blockquote></details>

Exactly, this will be for another PR otherwise it was getting too big...

---

*[packages/agent-ui/src/containers/appendSegmentDialog.js, line 81 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/120#-KypkDqWwND-Nf9TgRAO:-KypmWq3aghvdNytDt7y:bilplbr) ([raw file](https://github.com/stratumn/indigo-js/blob/fe2542b5631c4713bb97cc8469a228720bd48dc2/packages/agent-ui/src/containers/appendSegmentDialog.js#L81)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

it seems that you only use `state.appendSegment` from state. Maybe use some ES6 destructuring from the top here? you would get rid of all the `state.*`
</blockquote></details>

Good point, I'll do this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/120)*

**Comment by jeremie-stratumn** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/120#-:-KypnF4nu-JsW7qIyN9u:bnfp4nl)*

**Pull request merged**
