### PR TITLE
agent-js: implement process.findSegmentsForPagination

### PR DESCRIPTION
**Pull request by jeremie-stratumn**
Here I implement  new `findSegments` function for better pagination experience. related to https://github.com/stratumn/indigo-js/issues/230. 

I am wondering how I should expose this via http api?

Next step would be to have agent-client-js `findSegments` when `limit=-1` call this `findSegmentsForPagination`.

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/indigo-js/231)

### CODE REVIEW

**Comment by such** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[packages/agent-js/src/process.js, line 315 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/231#-L2QrKzuFNT78zaPf1Oz:-L2QrKzuFNT78zaPf1P-:br8j8lg) ([raw file](https://github.com/stratumn/indigo-js/blob/24f057b23f553671f1ef38ce770deffa5bed90a9/packages/agent-js/src/process.js#L315)):*
> ```JavaScript
>           segmentsFound.push(...filteredSegments);
>           hasMore = foundThisTime === options.limit;
>           keepSearching = hasMore && segmentsFound.length < limit;
> ```

Since you have `limit == options.limit`, `keepSearching` will always be `false` I think. And you don't need a promiseWhile loop. Am I missing something?

---

*[packages/agent-js/src/promiseWhile.js, line 1 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/231#-L2QpqFjlFCfhfzch_FJ:-L2QpqFjlFCfhfzch_FK:bakxsds) ([raw file](https://github.com/stratumn/indigo-js/blob/24f057b23f553671f1ef38ce770deffa5bed90a9/packages/agent-js/src/promiseWhile.js#L1)):*
> ```JavaScript
> import co from 'co';
> ```

I don't know if it's relevant but we have a different implementation of `promiseWhile` in `agent-client-js`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/231)*

**Comment by such** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[packages/agent-js/src/process.js, line 315 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/231#-L2QrKzuFNT78zaPf1Oz:-L2QsEC2CzNyKfndK_Y6:b5s8yaz) ([raw file](https://github.com/stratumn/indigo-js/blob/24f057b23f553671f1ef38ce770deffa5bed90a9/packages/agent-js/src/process.js#L315)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

Since you have `limit == options.limit`, `keepSearching` will always be `false` I think. And you don't need a promiseWhile loop. Am I missing something?
</blockquote></details>

ok got it. I had missed the `filterSegment` part sorry.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/231)*

**Comment by such** [comment]
If I understand correctly `findSegments` is bugged as well. Don't we want to fix it and use it in this implementation?

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/231#-:-L2QtcJueELWH6cXRJXU:b-riwc6f)*

**Comment by t-bast** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[packages/agent-js/package.json, line 45 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/231#-L2QthOOKCVWq6C665Um:-L2QthOQEJRPOr_Wmm-Y:b-9fa8kg) ([raw file](https://github.com/stratumn/indigo-js/blob/24f057b23f553671f1ef38ce770deffa5bed90a9/packages/agent-js/package.json#L45)):*
> ```JSON
>     "qs": "^6.5.1",
>     "request": "^2.73.0",
>     "sinon": "^4.1.4",
> ```

sinon should be in the dev dependencies

---

*[packages/agent-js/src/process.js, line 303 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/231#-L2QuDpxITfVVygo4Yeo:-L2QuDpxITfVVygo4Yep:b6v6klg) ([raw file](https://github.com/stratumn/indigo-js/blob/24f057b23f553671f1ef38ce770deffa5bed90a9/packages/agent-js/src/process.js#L303)):*
> ```JavaScript
>     let hasMore;
>     const condition = () => keepSearching;
>     const body = () => {
> ```

Maybe rename to findSegmentsChunk? Or findSegmentsPage? And it would be cleaner and less error-prone if it took nextOffset and nextLimit as input instead of using a closure (especially in JS where closures are a mess to get right).
I'm thinking that this function could return the parameters that would be fed to the next iteration (offset, limit, hasMore, etc)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/231)*

**Comment by jeremie-stratumn** [comment]
It is tricky.. because of the return value of `findSegments` as opposed to `findSegmentsForPagination`..

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[packages/agent-js/package.json, line 45 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/231#-L2QthOOKCVWq6C665Um:-L2QwKtSpHr6o4139pHi:ba7m1n3) ([raw file](https://github.com/stratumn/indigo-js/blob/24f057b23f553671f1ef38ce770deffa5bed90a9/packages/agent-js/package.json#L45)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

sinon should be in the dev dependencies
</blockquote></details>

indeed, my bad

---

*[packages/agent-js/src/process.js, line 303 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/231#-L2QuDpxITfVVygo4Yeo:-L2QxNaqe5Ii5JeP12Jf:b-ehbcma) ([raw file](https://github.com/stratumn/indigo-js/blob/24f057b23f553671f1ef38ce770deffa5bed90a9/packages/agent-js/src/process.js#L303)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Maybe rename to findSegmentsChunk? Or findSegmentsPage? And it would be cleaner and less error-prone if it took nextOffset and nextLimit as input instead of using a closure (especially in JS where closures are a mess to get right).
I'm thinking that this function could return the parameters that would be fed to the next iteration (offset, limit, hasMore, etc)
</blockquote></details>

I can change the name of the function from `body` to `findSegmentsChunk` yes. But I cannot  pass arguments around as I would loose the genericity of `promiseWhile` function..

---

*[packages/agent-js/src/promiseWhile.js, line 1 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/231#-L2QpqFjlFCfhfzch_FJ:-L2QwhSS6e0FqteGEUpj:bd3n8a4) ([raw file](https://github.com/stratumn/indigo-js/blob/24f057b23f553671f1ef38ce770deffa5bed90a9/packages/agent-js/src/promiseWhile.js#L1)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

I don't know if it's relevant but we have a different implementation of `promiseWhile` in `agent-client-js`.
</blockquote></details>

Yes I saw that. I was experimenting with promise based generators which is quite powerful. I think this `promiseWhile` implementation is cleaner and shorter than the other one, don;t you think?

I wonder where I should put a common implementation for it between agent-js and agent-client-js? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/231#-:-L2Qy1lNrrOLZSqcGWJr:bal6iua)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[packages/agent-js/src/process.js, line 303 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/231#-L2QuDpxITfVVygo4Yeo:-L2R-4ki-jIySY6PyklL:b4l3tdq) ([raw file](https://github.com/stratumn/indigo-js/blob/24f057b23f553671f1ef38ce770deffa5bed90a9/packages/agent-js/src/process.js#L303)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

I can change the name of the function from `body` to `findSegmentsChunk` yes. But I cannot  pass arguments around as I would loose the genericity of `promiseWhile` function..
</blockquote></details>

But can't promiseWhile use the return value of iteration N of the "body" function and set it as input to the iteration N + 1 ?
It feels cleaner than sharing variables directly

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/231)*

**Comment by jeremie-stratumn** [comment]
After chatting with @such , I will directly change `process#findSegments()` function (breaking change).

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[packages/agent-js/src/process.js, line 303 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/231#-L2QuDpxITfVVygo4Yeo:-L2R1MHC-SSeLYak2dNm:b6dug2y) ([raw file](https://github.com/stratumn/indigo-js/blob/24f057b23f553671f1ef38ce770deffa5bed90a9/packages/agent-js/src/process.js#L303)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

But can't promiseWhile use the return value of iteration N of the "body" function and set it as input to the iteration N + 1 ?
It feels cleaner than sharing variables directly
</blockquote></details>

I see, let me try that.

---

*[packages/agent-js/src/promiseWhile.js, line 1 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/231#-L2QpqFjlFCfhfzch_FJ:-L2R1PW5pyiEg5obdGoJ:b9s1znb) ([raw file](https://github.com/stratumn/indigo-js/blob/24f057b23f553671f1ef38ce770deffa5bed90a9/packages/agent-js/src/promiseWhile.js#L1)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

Yes I saw that. I was experimenting with promise based generators which is quite powerful. I think this `promiseWhile` implementation is cleaner and shorter than the other one, don;t you think?

I wonder where I should put a common implementation for it between agent-js and agent-client-js? 
</blockquote></details>

I will create a new npm package `@indigoframework/utils` and put it there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/231#-:-L2R0nzAKjiwuUhdmHHL:b58woiz)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[packages/agent-js/src/process.js, line 294 at r2](https://reviewable.io:443/reviews/stratumn/indigo-js/231#-L2U8lKUz9JmSm2-U4dG:-L2U8lKVgx978CmrfEWs:byd6s6c) ([raw file](https://github.com/stratumn/indigo-js/blob/111bbf153be279e3a9b703821d8240d0601f59e3/packages/agent-js/src/process.js#L294)):*
> ```JavaScript
>    * @param {string[]} [opts.linkHashes] - an array of linkHashes the segments must have
>    * @param {string[]} [opts.tags] - an array of tags the segments must have
>    * @returns {Promise} - a promise that resolve with the an object containing segments found and other info related to pagination
> ```

nit: typos/grammar: "resolves", "the an"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/231#-:-L2UADKRko6VB76wy1Zg:bnfp4nl)*

**Comment by such** [comment]
Reviewed 30 of 30 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[packages/agent-client-js/rollup.browser.config.js, line 10 at r3](https://reviewable.io:443/reviews/stratumn/indigo-js/231#-L2u1BM9pZ1LBjwbeoPB:-L2u1BM9pZ1LBjwbeoPC:b-xma6au) ([raw file](https://github.com/stratumn/indigo-js/blob/7558db349284e034af03b561eff544cf1ed060ca/packages/agent-client-js/rollup.browser.config.js#L10)):*
> ```JavaScript
> const external = Object.keys(pkg.dependencies);
> 
> config.external = external;
> ```

The reason why we were not doing that is because it was meant to be used either with bower were most node dependencies are not available or standalone where it's a pain to add all the needed deps in the right order. So having all dependencies as external defeats the purpose of that. We should either decide not to maintain this build anymore or make it work with the external dependencies.

---

*[packages/utils/src/index.js, line 1 at r3](https://reviewable.io:443/reviews/stratumn/indigo-js/231#-L2u4GJXvhUOQj7kkVtU:-L2u4GJXvhUOQj7kkVtV:bq0oc45) ([raw file](https://github.com/stratumn/indigo-js/blob/7558db349284e034af03b561eff544cf1ed060ca/packages/utils/src/index.js#L1)):*
> ```JavaScript
> /* eslint-disable */
> ```

we should disable only the rule that fails

---

*[packages/utils/src/promiseWhile/promiseWhile.test.js, line 20 at r3](https://reviewable.io:443/reviews/stratumn/indigo-js/231#-L2u4QLLR4qvvD3yTPrC:-L2u4QLLR4qvvD3yTPrD:b-cktvx3) ([raw file](https://github.com/stratumn/indigo-js/blob/7558db349284e034af03b561eff544cf1ed060ca/packages/utils/src/promiseWhile/promiseWhile.test.js#L20)):*
> ```JavaScript
>     return promiseWhile(condition, body, arg).then(({ res }) => {
>       expect(res).to.have.lengthOf(10);
>       // res.length.should.be.eql(10);
> ```

nit: commented code

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/231)*

**Comment by jeremie-stratumn** [comment]
thanx @such for the help with rollup!
mapexplorer-core was failing because of the signature change in the response of agent-client-js `findSegments`. Justy to be clear that the signature of the client's function has change!

---

Review status: 27 of 37 files reviewed at latest revision, 5 unresolved discussions.

---

*[packages/agent-js/src/process.js, line 294 at r2](https://reviewable.io:443/reviews/stratumn/indigo-js/231#-L2U8lKUz9JmSm2-U4dG:-L2xqaG_2ZOVyjXpaaI-:bb7f2mf) ([raw file](https://github.com/stratumn/indigo-js/blob/111bbf153be279e3a9b703821d8240d0601f59e3/packages/agent-js/src/process.js#L294)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit: typos/grammar: "resolves", "the an"
</blockquote></details>

done

---

*[packages/utils/src/index.js, line 1 at r3](https://reviewable.io:443/reviews/stratumn/indigo-js/231#-L2u4GJXvhUOQj7kkVtU:-L2xqZ1miXNHIgDfOqpq:b-7rl0kd) ([raw file](https://github.com/stratumn/indigo-js/blob/7558db349284e034af03b561eff544cf1ed060ca/packages/utils/src/index.js#L1)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

we should disable only the rule that fails
</blockquote></details>

done

---

*[packages/utils/src/promiseWhile/promiseWhile.test.js, line 20 at r3](https://reviewable.io:443/reviews/stratumn/indigo-js/231#-L2u4QLLR4qvvD3yTPrC:-L2xr7638oJZLcwUcljD:bb7f2mf) ([raw file](https://github.com/stratumn/indigo-js/blob/7558db349284e034af03b561eff544cf1ed060ca/packages/utils/src/promiseWhile/promiseWhile.test.js#L20)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

nit: commented code
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/231#-:-L2xrADsf9D4SdQuOTeh:b6ffq1r)*

**Comment by such** [comment]
:lgtm:

---

Reviewed 1 of 30 files at r3, 6 of 6 files at r4, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/231#-:-L2yOGwnCauroYNqmfUo:bnfp4nl)*

**Pull request merged**
