### PR TITLE
tmpop-explorer: build library before publishing

### PR DESCRIPTION
**Pull request by such**
This change is [Reviewable](https://reviewable.io/reviews/stratumn/indigo-js/196)

### CODE REVIEW

**Comment by t-bast** [comment]
Makes sense, thanks for spotting this!

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/196#-:-L0shyxwWA4_46x1Wczq:b-5p1och)*

**Comment by t-bast** [comment]
Reviewed 33 of 33 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[packages/tmpop-explorer/package.json, line 54 at r2](https://reviewable.io:443/reviews/stratumn/indigo-js/196#-L0tXBhFdOrq-MyuAiu7:-L0tXBhFdOrq-MyuAiu8:b-1qoi9w) ([raw file](https://github.com/stratumn/indigo-js/blob/8d1279712a9fd765bf71bb3d4ce1cf2d60c2f2a9/packages/tmpop-explorer/package.json#L54)):*
> ```JSON
>     "build": "rollup -c",
>     "start": "rollup -c -w",
>     "version:app": "sed -i \"s#\\\"version\\\": \\\".*\\\"#\\\"version\\\": \\\"$npm_package_version\\\"#g\" ./app/package.json",
> ```

Do you think it's worth doing that sed magic on the example too?

---

*[packages/tmpop-explorer/README.md, line 7 at r2](https://reviewable.io:443/reviews/stratumn/indigo-js/196#-L0tW5HRdF4IX406cZNU:-L0tW5HRdF4IX406cZNV:b-1d742) ([raw file](https://github.com/stratumn/indigo-js/blob/8d1279712a9fd765bf71bb3d4ce1cf2d60c2f2a9/packages/tmpop-explorer/README.md#L7)):*
> ```Markdown
> [npm](https://www.npmjs.com/package/@indigoframework/tmpop-explorer)
> 
> #### Local Development
> ```

nit: no reason to add more ##

---

*[packages/tmpop-explorer/README.md, line 9 at r2](https://reviewable.io:443/reviews/stratumn/indigo-js/196#-L0tWE4tGL0q-pebuzvy:-L0tWE4tGL0q-pebuzvz:b-vqejqx) ([raw file](https://github.com/stratumn/indigo-js/blob/8d1279712a9fd765bf71bb3d4ce1cf2d60c2f2a9/packages/tmpop-explorer/README.md#L9)):*
> ```Markdown
> #### Local Development
> 
> Now you're ready to run a local version of rollup that will watch your `src/` component and automatically recompile it into `dist/` whenever you make changes.
> ```

nit: this sentence is a bit weird; I don't understand the "now" since it's the beginning of the steps

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/196)*

**Comment by such** [comment]
Review status: 31 of 32 files reviewed at latest revision, 3 unresolved discussions.

---

*[packages/tmpop-explorer/package.json, line 54 at r2](https://reviewable.io:443/reviews/stratumn/indigo-js/196#-L0tXBhFdOrq-MyuAiu7:-L0tZBH9RIvqu3zfT_kL:binuwhb) ([raw file](https://github.com/stratumn/indigo-js/blob/8d1279712a9fd765bf71bb3d4ce1cf2d60c2f2a9/packages/tmpop-explorer/package.json#L54)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Do you think it's worth doing that sed magic on the example too?
</blockquote></details>

this is not on the example :)

---

*[packages/tmpop-explorer/README.md, line 7 at r2](https://reviewable.io:443/reviews/stratumn/indigo-js/196#-L0tW5HRdF4IX406cZNU:-L0tZEd-OjDe1NolQ3JK:b-896fix) ([raw file](https://github.com/stratumn/indigo-js/blob/8d1279712a9fd765bf71bb3d4ce1cf2d60c2f2a9/packages/tmpop-explorer/README.md#L7)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit: no reason to add more ##
</blockquote></details>

Done.

---

*[packages/tmpop-explorer/README.md, line 9 at r2](https://reviewable.io:443/reviews/stratumn/indigo-js/196#-L0tWE4tGL0q-pebuzvy:-L0tZGVXX5fRJX4zobBg:bgcs2of) ([raw file](https://github.com/stratumn/indigo-js/blob/8d1279712a9fd765bf71bb3d4ce1cf2d60c2f2a9/packages/tmpop-explorer/README.md#L9)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit: this sentence is a bit weird; I don't understand the "now" since it's the beginning of the steps
</blockquote></details>

Savage copy pasting... Done. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/196)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/196#-:-L0t_JWop8TJ1DLldD3t:bnfp4nl)*

**Pull request merged**
