### PR TITLE
add option to not focus on segment

### PR DESCRIPTION
**Pull request by bejito**
Add an option to not focus on segment on click

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/indigo-js/233)

### CODE REVIEW

**Comment by jeremie-stratumn** [comment]
Could you add a test?

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/233#-:-L3N0K5E8_svS3zQHf1b:bpg7ife)*

**Comment by simonvadee** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/233#-:-L3Ot31M8AB3VJaxxMOk:bnfp4nl)*

**Comment by such** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/233#-:-L3SFLfZEfnF6k29aIz9:bnfp4nl)*

**Comment by such** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[packages/mapexplorer-core/test/integration/ChainTree.test.js, line 210 at r2](https://reviewable.io:443/reviews/stratumn/indigo-js/233#-L3T62_MdmTS2B5CgOvf:-L3T62_MdmTS2B5CgOvg:ba3ce01) ([raw file](https://github.com/stratumn/indigo-js/blob/d5b3d7b18d70f830aeb772e59f44514410716c03/packages/mapexplorer-core/test/integration/ChainTree.test.js#L210)):*
> ```JavaScript
>   });
> 
>   describe('with spacific options', () => {
> ```

typo: specific

---

*[packages/mapexplorer-core/test/integration/ChainTree.test.js, line 216 at r2](https://reviewable.io:443/reviews/stratumn/indigo-js/233#-L3T66XadAGp_KadyhPo:-L3T66XadAGp_KadyhPp:b-hfpv1m) ([raw file](https://github.com/stratumn/indigo-js/blob/d5b3d7b18d70f830aeb772e59f44514410716c03/packages/mapexplorer-core/test/integration/ChainTree.test.js#L216)):*
> ```JavaScript
> 
>     it('should disable withFocus', () => {
>       // const options = { ...defaultOptions, withFocus: false };
> ```

remove?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/233)*

**Comment by bejito** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[packages/mapexplorer-core/test/integration/ChainTree.test.js, line 210 at r2](https://reviewable.io:443/reviews/stratumn/indigo-js/233#-L3T62_MdmTS2B5CgOvf:-L3T6YiS3kAYb3V12oxJ:b-896fix) ([raw file](https://github.com/stratumn/indigo-js/blob/d5b3d7b18d70f830aeb772e59f44514410716c03/packages/mapexplorer-core/test/integration/ChainTree.test.js#L210)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

typo: specific
</blockquote></details>

Done.

---

*[packages/mapexplorer-core/test/integration/ChainTree.test.js, line 216 at r2](https://reviewable.io:443/reviews/stratumn/indigo-js/233#-L3T66XadAGp_KadyhPo:-L3T6Z6iApSffW4_t6XH:b-896fix) ([raw file](https://github.com/stratumn/indigo-js/blob/d5b3d7b18d70f830aeb772e59f44514410716c03/packages/mapexplorer-core/test/integration/ChainTree.test.js#L216)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

remove?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/233)*

**Comment by simonvadee** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/233#-:-L3TAnJ7pDf23at_4qRo:bnfp4nl)*

**Pull request merged**
