### PR TITLE
agent-js: default and max limit for memoryStore (#90)

### PR DESCRIPTION
**Pull request by bejito**
To be consistent with https://github.com/stratumn/sdk/blob/master/store/store.go#L23

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/indigo-js/151)

### CODE REVIEW

**Comment by t-bast** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[packages/agent-js/test/memoryStore.js, line 98 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/151#-L-Cjbw22inxzDRPvXrq:-L-Cjbw22inxzDRPvXrr:bjvmb89) ([raw file](https://github.com/stratumn/indigo-js/blob/3d1062dfb454827a783a87e8e12b219fd82d8f6b/packages/agent-js/test/memoryStore.js#L98)):*
> ```JavaScript
>       // Save >20 segments
> 
>       const generateSegment = h => ({
> ```

nit: maybe a generateRandomSegment() function would be useful.
This way it could set a valid linkHash (which is not the case here).

---

*[packages/agent-js/test/memoryStore.js, line 120 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/151#-L-Ck4RXV0UrIGMueUTs:-L-Ck4RXV0UrIGMueUTt:bjtbb1a) ([raw file](https://github.com/stratumn/indigo-js/blob/3d1062dfb454827a783a87e8e12b219fd82d8f6b/packages/agent-js/test/memoryStore.js#L120)):*
> ```JavaScript
> 
>       // Check that response only has 20 segments
>       store
> ```

You need to return this.
Otherwise the then executes outside of the scope of the test method, so even if it fails the test will pass.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/151)*

**Comment by bejito** [comment]
*[packages/agent-js/test/memoryStore.js, line 98 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/151#-L-Cjbw22inxzDRPvXrq:-L-CkyJ7V6ZGyR71WvfO:b-h8bz1e) ([raw file](https://github.com/stratumn/indigo-js/blob/3d1062dfb454827a783a87e8e12b219fd82d8f6b/packages/agent-js/test/memoryStore.js#L98)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit: maybe a generateRandomSegment() function would be useful.
This way it could set a valid linkHash (which is not the case here).
</blockquote></details>

It could in deed be useful in a more general case. This is enough though in my test case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/151)*

**Comment by bejito** [comment]
*[packages/agent-js/test/memoryStore.js, line 120 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/151#-L-Ck4RXV0UrIGMueUTs:-L-ClOd8ZeoifmHwv-Qo:b-8fx2u7) ([raw file](https://github.com/stratumn/indigo-js/blob/3d1062dfb454827a783a87e8e12b219fd82d8f6b/packages/agent-js/test/memoryStore.js#L120)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

You need to return this.
Otherwise the then executes outside of the scope of the test method, so even if it fails the test will pass.
</blockquote></details>

:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/151)*

**Comment by conord33** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[packages/agent-js/src/memoryStore.js, line 33 at r2](https://reviewable.io:443/reviews/stratumn/indigo-js/151#-L-CqOb3j5qHwdKD4OO_:-L-CqOb3j5qHwdKD4OOa:bob17eq) ([raw file](https://github.com/stratumn/indigo-js/blob/8497b9d38238906d1aa2e151f7cef40a04a52164/packages/agent-js/src/memoryStore.js#L33)):*
> ```JavaScript
>   if (opts.limit) {
>     if (opts.limit > STORE_MAX_LIMIT) {
>       const err = new Error('maximum limit should be 200');
> ```

I think you should template the error message since it is referring to the STORE_MAX_LIMIT. 

new Error('maximum limit should be 200'); -> new Error(`maximum limit should be ${STORE_MAX_LIMIT}`);

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/151)*

**Comment by conord33** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/151#-:-L-CsLu5vncnwqYbP3wZ:bnfp4nl)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/151#-:-L-CyoL7ioyjTvGyN-Yd:bnfp4nl)*

**Comment by t-bast** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/151)*

**Comment by bejito** [comment]
*[packages/agent-js/src/memoryStore.js, line 33 at r2](https://reviewable.io:443/reviews/stratumn/indigo-js/151#-L-CqOb3j5qHwdKD4OO_:-L-D3uSycSrXVSPFazZi:b-896fix) ([raw file](https://github.com/stratumn/indigo-js/blob/8497b9d38238906d1aa2e151f7cef40a04a52164/packages/agent-js/src/memoryStore.js#L33)):*
<details><summary><i>Previously, conord33 (Conor Dawson) wrote…</i></summary><blockquote>

I think you should template the error message since it is referring to the STORE_MAX_LIMIT. 

new Error('maximum limit should be 200'); -> new Error(`maximum limit should be ${STORE_MAX_LIMIT}`);
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/151)*

**Pull request merged**
