### PR TITLE
agent-ui: pretty layout

### PR DESCRIPTION
**Pull request by t-bast**
Style the left navigation, top bar and main content to match the existing agent UI.
The left navigation is now finally Indigo ! :)

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/indigo-js/135)

### CODE REVIEW

**Comment by jeremie-stratumn** [comment]
Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[packages/agent-ui/src/containers/leftNavigation.js, line 171 at r2](https://reviewable.io:443/reviews/stratumn/indigo-js/135#-KzPTL9_NNkmF1Txkd7T:-KzPTL9_NNkmF1Txkd7U:b4g8bd1) ([raw file](https://github.com/stratumn/indigo-js/blob/5d6642273257bf16d64846740d40b2a5fd030864/packages/agent-ui/src/containers/leftNavigation.js#L171)):*
> ```JavaScript
> export function mapStateToProps(state, ownProps) {
>   const { pathname } = ownProps.location;
>   const pathParts = pathname.split('/');
> ```

I wonder if you could use the `match.params` object provided by react router. You'll have the agent and process param directly spelt out for you..
https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/match.md

---

*[packages/agent-ui/src/containers/topBar.js, line 31 at r2](https://reviewable.io:443/reviews/stratumn/indigo-js/135#-KzPTo7rg4-LGGRStmFX:-KzPTo7rg4-LGGRStmFY:b-nij6uf) ([raw file](https://github.com/stratumn/indigo-js/blob/5d6642273257bf16d64846740d40b2a5fd030864/packages/agent-ui/src/containers/topBar.js#L31)):*
> ```JavaScript
>       <div style={{ display: 'flex' }} key={p}>
>         <Typography type="headline" style={{ color: 'gray' }}>
>           &nbsp;&gt;&nbsp;
> ```

Would you mind adding a comment explaining what this translate to?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/135)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[packages/agent-ui/src/containers/leftNavigation.js, line 171 at r2](https://reviewable.io:443/reviews/stratumn/indigo-js/135#-KzPTL9_NNkmF1Txkd7T:-KzPV0POG0uuZ7LcCnjr:blr36fk) ([raw file](https://github.com/stratumn/indigo-js/blob/5d6642273257bf16d64846740d40b2a5fd030864/packages/agent-ui/src/containers/leftNavigation.js#L171)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

I wonder if you could use the `match.params` object provided by react router. You'll have the agent and process param directly spelt out for you..
https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/match.md

</blockquote></details>

Unfortunately not because the leftNav isn't rendered via a Route (it's rendered for all routes). So it doesn't receive a match.params since there isn't anything to match :)

---

*[packages/agent-ui/src/containers/topBar.js, line 31 at r2](https://reviewable.io:443/reviews/stratumn/indigo-js/135#-KzPTo7rg4-LGGRStmFX:-KzPVEJnMBrf0coICOu3:b-jpcmcr) ([raw file](https://github.com/stratumn/indigo-js/blob/5d6642273257bf16d64846740d40b2a5fd030864/packages/agent-ui/src/containers/topBar.js#L31)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

Would you mind adding a comment explaining what this translate to?
</blockquote></details>

Of course, I'll add that

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/135)*

**Comment by t-bast** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[packages/agent-ui/src/containers/topBar.js, line 31 at r2](https://reviewable.io:443/reviews/stratumn/indigo-js/135#-KzPTo7rg4-LGGRStmFX:-KzPW0wW8wtaH1KzFbmS:b-896fix) ([raw file](https://github.com/stratumn/indigo-js/blob/5d6642273257bf16d64846740d40b2a5fd030864/packages/agent-ui/src/containers/topBar.js#L31)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Of course, I'll add that
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/135)*

**Comment by jeremie-stratumn** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[packages/agent-ui/src/containers/leftNavigation.js, line 171 at r2](https://reviewable.io:443/reviews/stratumn/indigo-js/135#-KzPTL9_NNkmF1Txkd7T:-KzPWZ0e5dDIra3pNVd6:b4jny60) ([raw file](https://github.com/stratumn/indigo-js/blob/5d6642273257bf16d64846740d40b2a5fd030864/packages/agent-ui/src/containers/leftNavigation.js#L171)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Unfortunately not because the leftNav isn't rendered via a Route (it's rendered for all routes). So it doesn't receive a match.params since there isn't anything to match :)
</blockquote></details>

Ah good point! That's fine then. We could eventually put it under a route with only optionals: /:agent?/:process?/:rest?. What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/135)*

**Comment by jeremie-stratumn** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/135#-:-KzPXXmticpa2NPTWlZy:bnfp4nl)*

**Pull request merged**
