### PR TITLE
agent-client-js: safely concatenate agent url

### LINKED ISSUE #142: agent-client: remove agent url spurious '/' at the end
### Expected behavior
```
getAgent('http://myagent:3000/').then(agent => agent.getProcess('p').getMapIds())
```
should work

### Actual behavior
The server returned a status of 404 for the request "GET http://myagent:3000//p/maps"

the issue comes from the last '/' in the agent url

### PR DESCRIPTION
**Pull request by simonvadee**
Fix #142

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/indigo-js/155)

### CODE REVIEW

**Comment by conord33** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/155#-:-L-VrHhQWonfHeauy5c8:bnfp4nl)*

**Comment by alexppxela** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/155#-:-L-VrUfqUXqcMV0Odfds:bnfp4nl)*

**Comment by such** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/155#-:-L-WJyPhNuEXqffrkNT9:bnfp4nl)*

**Comment by jeremie-stratumn** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/155#-:-L-Wb9I1sKNwK5T81yUY:bnfp4nl)*

**Pull request merged**
