### PR TITLE
agent-ui: append segment action reducer

### PR DESCRIPTION
**Pull request by t-bast**
Add actions and reducer for append segment.
Will plug the UI in a later PR.
Also fixed an issue with the actionTypes export that made webpack fail locally.

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/indigo-js/109)

### CODE REVIEW

**Comment by jeremie-stratumn** [comment]
overall good! Just a couple comments below

---

Review status: 0 of 26 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[packages/agent-ui/src/reducers/appendSegment.js, line 15 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/109#-KyQ7pebMyCyKYjjHgFy:-KyQ7pebMyCyKYjjHgFz:by66lqk) ([raw file](https://github.com/stratumn/indigo-js/blob/cdd30bf426faf1326353288a178441df2ac5a81b/packages/agent-ui/src/reducers/appendSegment.js#L15)):*
> ```JavaScript
>         parent: action.parent,
>         actions: action.actions,
>         selectedAction: Object.keys(action.actions)[0]
> ```

Are you sure action.actions always has at least one element?

---

*[packages/agent-ui/src/reducers/appendSegment.js, line 18 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/109#-KyQ86J59rngQcnMGRTX:-KyQ86J59rngQcnMGRTY:b24t1wj) ([raw file](https://github.com/stratumn/indigo-js/blob/cdd30bf426faf1326353288a178441df2ac5a81b/packages/agent-ui/src/reducers/appendSegment.js#L18)):*
> ```JavaScript
>       };
>     case actionTypes.APPEND_SEGMENT_DIALOG_SELECT_ACTION:
>       if (Object.keys(state.actions).includes(action.action)) {
> ```

what do you have in mind here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/109#-:-KyQ8OjlnnjCUXKu6tNn:b-vh2bdm)*

**Comment by jeremie-stratumn** [comment]
Reviewed 26 of 26 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/109)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[packages/agent-ui/src/reducers/appendSegment.js, line 15 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/109#-KyQ7pebMyCyKYjjHgFy:-KyQKMNoN_jGyr0xo4w7:bl43zyt) ([raw file](https://github.com/stratumn/indigo-js/blob/cdd30bf426faf1326353288a178441df2ac5a81b/packages/agent-ui/src/reducers/appendSegment.js#L15)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

Are you sure action.actions always has at least one element?
</blockquote></details>

No but that's ok, there is a unit test showing that in case there's no element this ends up "undefined" which is what we want

---

*[packages/agent-ui/src/reducers/appendSegment.js, line 18 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/109#-KyQ86J59rngQcnMGRTX:-KyQJfIrGBpwjAcBdOKK:b-t25b88) ([raw file](https://github.com/stratumn/indigo-js/blob/cdd30bf426faf1326353288a178441df2ac5a81b/packages/agent-ui/src/reducers/appendSegment.js#L18)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

what do you have in mind here?
</blockquote></details>

The idea is that you can only select an action that's in the process actions list, otherwise it will be a no-op. Maybe not essential since the UI should not be allowing you to do that, but it feels safer :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/109)*

**Comment by jeremie-stratumn** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/109#-:-KyQZhCm67q6jw27Kogx:bnfp4nl)*

**Pull request merged**
