### PR TITLE
agent-ui: segment page

### PR DESCRIPTION
**Pull request by t-bast**
This pull request introduces a working segment details page.
* It loads the corresponding segment if needed.
* I also updated a route issue where we weren't very coherent between plural/singular.
* I added a redirection to the segment page when a new map is created

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/indigo-js/102)

### CODE REVIEW

**Comment by alexppxela** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/102)*

**Comment by jeremie-stratumn** [comment]
Looks great overall! Good job! One small thing inline

---

Review status: 12 of 20 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[packages/agent-ui/src/containers/segmentPage.js, line 38 at r3](https://reviewable.io:443/reviews/stratumn/indigo-js/102#-KxxmWQPp1tp0Mg-qrD9:-KxxmWQPp1tp0Mg-qrDA:b7fbudd) ([raw file](https://github.com/stratumn/indigo-js/blob/ffc82509c8442c4121323a911cb2468617f58fb7/packages/agent-ui/src/containers/segmentPage.js#L38)):*
> ```JavaScript
>     }
> 
>     return <div>{JSON.stringify(segment)}</div>;
> ```

I believe that this would produce a minified json string, right? You can use `JSON.stringify(segment, null, 2)` to prettify it.

---

*[packages/agent-ui/src/containers/segmentPage.js, line 79 at r3](https://reviewable.io:443/reviews/stratumn/indigo-js/102#-KxxlTGamNe-gJ_3I_qL:-KxxlTGamNe-gJ_3I_qM:b-flpq8x) ([raw file](https://github.com/stratumn/indigo-js/blob/ffc82509c8442c4121323a911cb2468617f58fb7/packages/agent-ui/src/containers/segmentPage.js#L79)):*
> ```JavaScript
>   props.status = status;
> 
>   if (status === statusTypes.LOADING) {
> ```

it could be interesting to use the pattern described on redux.js.org, see `fetchPostsIfNeeded` on this page: http://redux.js.org/docs/advanced/ExampleRedditAPI.html. See thislogic belongs to the action creator, as we may have to use it again at another location. So similarly we could have a `getSegmentIfNeeded` action and delegate it all this logic 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/102#-:-KxxnDfpdn7AkFmLmYuV:b6g1mjj)*

**Comment by t-bast** [comment]
Reviewed 20 of 20 files at r1, 8 of 8 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[packages/agent-ui/src/containers/segmentPage.js, line 38 at r3](https://reviewable.io:443/reviews/stratumn/indigo-js/102#-KxxmWQPp1tp0Mg-qrD9:-KxxndBwOZ5zcjJbFWI6:b-m724g1) ([raw file](https://github.com/stratumn/indigo-js/blob/ffc82509c8442c4121323a911cb2468617f58fb7/packages/agent-ui/src/containers/segmentPage.js#L38)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

I believe that this would produce a minified json string, right? You can use `JSON.stringify(segment, null, 2)` to prettify it.
</blockquote></details>

Neat, I didn't know that thanks. Updating this.

---

*[packages/agent-ui/src/containers/segmentPage.js, line 79 at r3](https://reviewable.io:443/reviews/stratumn/indigo-js/102#-KxxlTGamNe-gJ_3I_qL:-KxxoCdZbZsbn2kJL0Ob:b-tngoff) ([raw file](https://github.com/stratumn/indigo-js/blob/ffc82509c8442c4121323a911cb2468617f58fb7/packages/agent-ui/src/containers/segmentPage.js#L79)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

it could be interesting to use the pattern described on redux.js.org, see `fetchPostsIfNeeded` on this page: http://redux.js.org/docs/advanced/ExampleRedditAPI.html. See thislogic belongs to the action creator, as we may have to use it again at another location. So similarly we could have a `getSegmentIfNeeded` action and delegate it all this logic 
</blockquote></details>

Cool, that sounds cleaner indeed. Will move this logic to the action creator.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/102)*

**Comment by t-bast** [comment]
Review status: 16 of 20 files reviewed at latest revision, 2 unresolved discussions.

---

*[packages/agent-ui/src/containers/segmentPage.js, line 38 at r3](https://reviewable.io:443/reviews/stratumn/indigo-js/102#-KxxmWQPp1tp0Mg-qrD9:-Ky-z_fCSffsrh_EBQdH:b-896fix) ([raw file](https://github.com/stratumn/indigo-js/blob/ffc82509c8442c4121323a911cb2468617f58fb7/packages/agent-ui/src/containers/segmentPage.js#L38)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Neat, I didn't know that thanks. Updating this.
</blockquote></details>

Done.

---

*[packages/agent-ui/src/containers/segmentPage.js, line 79 at r3](https://reviewable.io:443/reviews/stratumn/indigo-js/102#-KxxlTGamNe-gJ_3I_qL:-Ky-zZsbMPoALttePok7:b-896fix) ([raw file](https://github.com/stratumn/indigo-js/blob/ffc82509c8442c4121323a911cb2468617f58fb7/packages/agent-ui/src/containers/segmentPage.js#L79)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Cool, that sounds cleaner indeed. Will move this logic to the action creator.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/102)*

**Comment by jeremie-stratumn** [comment]
:lgtm:

---

Review status: 16 of 20 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/102#-:-Ky0NNU-_l_TVpw-KRI6:bnfp4nl)*

**Comment by jeremie-stratumn** [comment]
Reviewed 8 of 20 files at r1, 8 of 8 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/102)*

**Pull request merged**
