### PR TITLE
agent-js: document HTTP API using OpenAPI 2.0

### PR DESCRIPTION
**Pull request by such**
This change is [Reviewable](https://reviewable.io/reviews/stratumn/indigo-js/131)

### CODE REVIEW

**Comment by t-bast** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[packages/agent-js/src/httpServer.js, line 568 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/131#-Kz-KJulH_DNjIBxnBvz:-Kz-KJulH_DNjIBxnBw-:bo4jxhw) ([raw file](https://github.com/stratumn/indigo-js/blob/4d3ea9277deeb72cc398a95a09206976969d46a7/packages/agent-js/src/httpServer.js#L568)):*
> ```JavaScript
>    */
>   app.get(
>     '/{process}/maps',
> ```

Shouldn't this still be :process ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/131)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/131#-:-Kz-Kh9Cy0uJoXbqxwIb:bnfp4nl)*

**Comment by such** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[packages/agent-js/src/httpServer.js, line 568 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/131#-Kz-KJulH_DNjIBxnBvz:-Kz-KcWc4qkGLJSnlKx2:b-kxmhdt) ([raw file](https://github.com/stratumn/indigo-js/blob/4d3ea9277deeb72cc398a95a09206976969d46a7/packages/agent-js/src/httpServer.js#L568)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Shouldn't this still be :process ?
</blockquote></details>

Indeed! That's what was caught by the test. I was in robot mode I guess

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/131)*

**Comment by such** [comment]
@stephan83, @t-bast, @jeremie-stratumn, @simonvadee, @piedup, @conord33, @alexppxela:

Is everybody ok with the fact that it makes `src/httpServer.js` pretty verbose? The alternative would be to use a different file (or to write the swagger.yaml directly and not use swagger-jsdoc).

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/131#-:-Kz-ODanDjPgxZaZmwPy:borg4wx)*

**Comment by simonvadee** [comment]
:lgtm:

---

Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/131#-:-Kz-RaZ1pDRzsxD5Gvsi:bnfp4nl)*

**Comment by conord33** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/131#-:-Kz-WnyxszqclqJ8AYwe:bnfp4nl)*

**Comment by t-bast** [comment]
Yep I think it's better to have this close to each API rather than in another file. If it was in another file we would forget to update it more easily :)

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/131#-:-Kz-eRToeoVxD6wgwoIi:b-p3g47k)*

**Comment by jeremie-stratumn** [comment]
:lgtm:
Agreed with @t-bast , better to have the swagger def close to the api endpoint.

---

Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/131#-:-Kz2gDs02j2vnHHWChjS:b-ri3wkc)*

**Pull request merged**
