### PR TITLE
agent-client-js: update FindSegments documentation on README

### PR DESCRIPTION
**Pull request by conord33**
This change is [Reviewable](https://reviewable.io/reviews/stratumn/indigo-js/125)

### CODE REVIEW

**Comment by such** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[packages/agent-client-js/README.md, line 194 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/125#-Kyv3WRYOQgvFI4hPmmM:-Kyv3WRYOQgvFI4hPmmN:baiibds) ([raw file](https://github.com/stratumn/indigo-js/blob/1dbfb18313469361f0bfdc06cae2ef2b48c8e411/packages/agent-client-js/README.md#L194)):*
> ```Markdown
> - `mapIds`: return segments with specified map ID
> - `prevLinkHash`: return segments with specified previous link hash
> - `linkHashes`: return segments match one of the linkHashes (array)
> ```

you're the english native here but I would have said "segments *that* match...". Is it missing?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/125)*

**Comment by conord33** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[packages/agent-client-js/README.md, line 194 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/125#-Kyv3WRYOQgvFI4hPmmM:-Kyv9dvH0XtGrVw5F3kj:b-o7k0wk) ([raw file](https://github.com/stratumn/indigo-js/blob/1dbfb18313469361f0bfdc06cae2ef2b48c8e411/packages/agent-client-js/README.md#L194)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

you're the english native here but I would have said "segments *that* match...". Is it missing?
</blockquote></details>

i was just testing you obviously...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/125)*

**Comment by such** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[packages/agent-client-js/README.md, line 194 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/125#-Kyv3WRYOQgvFI4hPmmM:-Kyv9tmQOccVNp0uRCa9:b32vir) ([raw file](https://github.com/stratumn/indigo-js/blob/1dbfb18313469361f0bfdc06cae2ef2b48c8e411/packages/agent-client-js/README.md#L194)):*
<details><summary><i>Previously, conord33 (Conor Dawson) wrote…</i></summary><blockquote>

i was just testing you obviously...
</blockquote></details>

;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/125)*

**Comment by t-bast** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/125#-:-KyvB0bZBrrYVs69Ksze:bnfp4nl)*

**Pull request merged**
