### PR TITLE
agent-ui: add redux-logger

### PR DESCRIPTION
**Pull request by jeremie-stratumn**
https://github.com/stratumn/indigo-js/issues/61

### CODE REVIEW

**Comment by t-bast** [comment]
I don't think this is necessary. This is already done by the redux devtools extension we're using which has a nicer UI, auto-diff features, etc.

**Comment by jeremie-stratumn** [comment]
the only added value I see is that one needs to install the redux devtools extension to use it on the browser, whereas logger is available to everyone via the console.. I totally agree that the devtools extension is amazing and much better than the logger. but still, could be nice to have the logger around to investigate an issue on someone's machine without having to install the devtools.

**Comment by t-bast** [comment]
I'm honestly not a fan. I don't like things that spam the console, and I don't like feature duplication...installing the extension tools literally takes 10 seconds, so I don't think it's a good reason to use the logger...

**Comment by jeremie-stratumn** [comment]
Fair enough, let's close this then :)

**Pull request closed without merging**
