### PR TITLE
agent-ui: create map with args

### PR DESCRIPTION
**Pull request by t-bast**
Fixing the assumption that the "init" method of a process takes a single argument.
It can have multiple arguments that we need to provide.

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/indigo-js/122)

### CODE REVIEW

**Comment by jeremie-stratumn** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[packages/agent-ui/src/containers/createMapDialog.js, line 45 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/122#-KytuHAWWr_PTaQ3UkYr:-KytuHAWWr_PTaQ3UkYs:b-r4xqlb) ([raw file](https://github.com/stratumn/indigo-js/blob/ed18bbeba92ac0fb4e0c5b5a91f96ab61a4d0a82/packages/agent-ui/src/containers/createMapDialog.js#L45)):*
> ```JavaScript
>   const initArgsWidgets = [];
>   for (let i = 0; i < args.length; i += 1) {
>     initArgs.push(undefined);
> ```

why do you push an undefined? Maybe add a comment to explain why you have to do this

---

*[packages/agent-ui/src/containers/createMapDialog.test.js, line 86 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/122#-KytvNCWF5e_XCq6exQ_:-KytvNCXx7tNVgwxTws3:b-hu7j0) ([raw file](https://github.com/stratumn/indigo-js/blob/ed18bbeba92ac0fb4e0c5b5a91f96ab61a4d0a82/packages/agent-ui/src/containers/createMapDialog.test.js#L86)):*
> ```JavaScript
>         .props().placeholder
>     ).to.equal('title');
>     dialog
> ```

I've just discovered the API to manipulate the value of an input: https://github.com/airbnb/enzyme/issues/76
```
wrapper.find('input').simulate('change', {target: {value: 'My new value'}});
```

I find it slightly more elegant than manipulating the DOM directly :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/122)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[packages/agent-ui/src/containers/createMapDialog.js, line 45 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/122#-KytuHAWWr_PTaQ3UkYr:-Kyu0Am-JoiliDYaUzd4:bmghpah) ([raw file](https://github.com/stratumn/indigo-js/blob/ed18bbeba92ac0fb4e0c5b5a91f96ab61a4d0a82/packages/agent-ui/src/containers/createMapDialog.js#L45)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

why do you push an undefined? Maybe add a comment to explain why you have to do this
</blockquote></details>

I need the array to be the same size than the arguments and the values to be uninitialized. I'll dig a bit more online to find the correct way to initialize an array with default values in JS.

---

*[packages/agent-ui/src/containers/createMapDialog.test.js, line 86 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/122#-KytvNCWF5e_XCq6exQ_:-Kyu0TJ99z8Z3j_MxCWB:bxlrcr5) ([raw file](https://github.com/stratumn/indigo-js/blob/ed18bbeba92ac0fb4e0c5b5a91f96ab61a4d0a82/packages/agent-ui/src/containers/createMapDialog.test.js#L86)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

I've just discovered the API to manipulate the value of an input: https://github.com/airbnb/enzyme/issues/76
```
wrapper.find('input').simulate('change', {target: {value: 'My new value'}});
```

I find it slightly more elegant than manipulating the DOM directly :)
</blockquote></details>

Agreed, thanks for the suggestion !

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/122)*

**Comment by t-bast** [comment]
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[packages/agent-ui/src/containers/createMapDialog.test.js, line 86 at r1](https://reviewable.io:443/reviews/stratumn/indigo-js/122#-KytvNCWF5e_XCq6exQ_:-KyvA8SqTbwxxgfW0MAO:b-d5af8t) ([raw file](https://github.com/stratumn/indigo-js/blob/ed18bbeba92ac0fb4e0c5b5a91f96ab61a4d0a82/packages/agent-ui/src/containers/createMapDialog.test.js#L86)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Agreed, thanks for the suggestion !
</blockquote></details>

Unfortunately this doesn't work, this is what the enzyme guys advise us to do: https://github.com/airbnb/enzyme/issues/364

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/122)*

**Comment by jeremie-stratumn** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/indigo-js/122#-:-KyvAm3S4d8or9I1zXaL:bnfp4nl)*

**Pull request merged**
